const {test}=require('node:test'),assert=require('node:assert/strict'),c=require('../lib/core');
const {aggregate}=require('../api/liquidity'),{pushes,slots}=require('../lib/control');
const a='0x73e5f588d27d6b5ec89c89c82692d1e7fecbd38b';
test('exact units include zero decimals and uint256',()=>{assert.equal(c.units(1000000000000000000000000001n,18),'1000000000.000000000000000001');assert.equal(c.units(0n,18),'0');assert.equal(c.units(100n,0),'100');assert.equal(c.units(100000n,3),'100');});
test('empty, short and malformed ABI words cannot become zero',()=>{for(const h of ['0x','0x00',null,'0xzz'])assert.throws(()=>c.uint(h));});
test('bounded metadata decoding rejects malicious lengths',()=>{assert.equal(c.string('0x'+'ff'.repeat(64)),null);assert.equal(c.string('0x'+Buffer.from('ARCY').toString('hex').padEnd(64,'0')),'ARCY');});
test('pairs must match chain and exact address; duplicates excluded',()=>{const p={chainId:'arc',pairAddress:'0x'+'a'.repeat(64),dexId:'uniswap',baseToken:{address:a},liquidity:{usd:10},volume:{h24:2}};const q={...p,pairAddress:'0x'+'b'.repeat(40),liquidity:{usd:30}};const x=aggregate([p,p,q,{...p,chainId:'ethereum'},{...p,baseToken:{address:'0x'+'1'.repeat(40)}}],a);assert.equal(x.pairCount,2);assert.equal(x.liquidityUsd,40);assert.equal(x.volume24h,4);assert.equal(x.lpStatus.status,'NOT_VERIFIED');assert.equal(aggregate([],a).liquidityUsd,null);assert.equal(aggregate([{...p,liquidity:{}}],a).liquidityUsd,null);assert.throws(()=>aggregate({},a));});
test('PUSH data is skipped; selectors are candidates only',()=>{assert.deepEqual(pushes('0x60406340c10f197f'+'63'.repeat(32)),['40c10f19']);assert.equal(slots.admin,'0xb53127684a568b3173ae13b9f8a6016e243e63b6e8ee1178d6a717850b5d6103');});
async function invoke(name,address=a){let code;const data=await require('../api/'+name)({method:'GET',query:{address}},{setHeader(){},status(n){code=n;return this},json(x){return x}});return {code,data};}
test('every route validates addresses before network use',async()=>{for(const n of ['token','supply','market','unlock','holders','control','liquidity','claims','mechanics'])assert.equal((await invoke(n,'invalid')).code,400);const config=require('../vercel.json');assert.deepEqual(config.rewrites.find(r=>r.source==='/api/activity'),{source:'/api/activity',destination:'/api/market?_arcyRoute=activity'});let code;await require('../api/market')({query:{address:'invalid',_arcyRoute:'activity'}},{setHeader(){},status(n){code=n;return this;},json(){}});assert.equal(code,400);assert.equal(require('fs').readdirSync(require('path').join(__dirname,'../api')).filter(n=>n.endsWith('.js')).length,12);});
test('external failure never becomes a factual negative',async()=>{const original=global.fetch;global.fetch=async()=>{throw Error('secret internal error')};try{for(const n of ['token','supply','market','holders','control','liquidity','mechanics']){const {data}=await invoke(n,'0x'+'d'.repeat(40));assert.equal(data.status,'NOT_VERIFIED');assert.ok(!JSON.stringify(data).includes('secret'));}assert.equal((await invoke('claims')).data.status,'NO_CLAIMS_SUPPLIED');assert.equal((await invoke('unlock')).data.nextUnlock.status,'NO_SOURCE_REPORTED_SCHEDULE');}finally{global.fetch=original;}});
test('optional metadata and burn failures preserve total supply at a pinned block',async()=>{const original=global.fetch;const word=n=>'0x'+BigInt(n).toString(16).padStart(64,'0');global.fetch=async(u,o)=>{const x=JSON.parse(o.body);let result;if(x.method==='eth_chainId')result='0x13b2';else if(x.method==='eth_blockNumber')result='0x123';else if(x.method==='eth_getCode')result='0x6000';else {assert.equal(x.params[1],'0x123');const s=x.params[0].data;if(s==='0x313ce567')result=word(18);else if(s==='0x18160ddd')result=word(1000000000000000000n);else return {ok:true,json:async()=>({error:{message:'unavailable'}})};}return {ok:true,json:async()=>({id:1,result})};};try{const t=(await invoke('token')).data;assert.equal(t.token.totalSupply,'1');assert.equal(t.token.name,null);const s=(await invoke('supply')).data;assert.equal(s.totalSupply.amount,'1');assert.equal(s.burnAddressBalance.status,'NOT_VERIFIED');}finally{global.fetch=original;}});
