const {test}=require('node:test'),assert=require('node:assert/strict'),f=require('../lib/fields'),h=require('../lib/holder-index'),c=require('../lib/core'),g=require('../lib/generic-contract');
const a='0x'+'a'.repeat(40),b='0x'+'b'.repeat(40),token='0x'+'c'.repeat(40),word=n=>'0x'+BigInt(n).toString(16).padStart(64,'0');
test('holder rankings exclude zero balances and burn custody, preserve supply denominator and reject incomplete coverage',()=>{const r=h.aggregate([[a,'600'],[b,'300'],[c.BURNS[1],'100'],[c.BURNS[0],'0'],[token,'0']],1000n,[]);assert.equal(r.holderCount,2);assert.equal(r.largestWalletPct,60);assert.equal(r.top10Pct,90);assert.equal(r.top20Pct,90);assert.throws(()=>h.aggregate([[a,'999']],1000n,[]));assert.throws(()=>h.aggregate([[a,'1'],[a,'999']],1000n,[]));assert.throws(()=>h.aggregate([[a,'0']],0n,[]));});
function log(from,to,value,index=0){return {address:token,blockNumber:'0x1',blockHash:'0x'+'1'.repeat(64),logIndex:'0x'+index.toString(16),removed:false,topics:[h.TRANSFER,word(from),word(to)],data:word(value)};}
test('event reconstruction handles mint, self transfer, burn, duplicates and rejects removed/inconsistent histories',()=>{const s={balances:{}};h.applyLogs(s,[log(c.BURNS[0],a,1000),log(a,b,300,1),log(a,a,1,2),log(b,c.BURNS[0],50,3)],token,0,2);assert.equal(s.balances[a],'700');assert.equal(s.balances[b],'250');const one={balances:{}};const minted=log(c.BURNS[0],a,1000);h.applyLogs(one,[minted,minted],token,0,2);assert.equal(one.balances[a],'1000');assert.throws(()=>h.applyLogs({balances:{}},[{...minted,removed:true}],token,0,2));assert.throws(()=>h.applyLogs({balances:{}},[log(a,b,1)],token,0,2));});
test('fallback source failure cannot erase later success and successful source stops lower-priority adapters',async()=>{const calls=[];const r=await f.resolve([{name:'market',tier:'MARKET_API_VERIFIED',read:async()=>{calls.push('market');return f.field(20,'MARKET_API_VERIFIED','market');}},{name:'chain',tier:'ONCHAIN_VERIFIED',read:async()=>{calls.push('chain');throw Object.assign(Error(),{httpStatus:530});}},{name:'docs',tier:'OFFICIAL_DOCUMENTATION',read:async()=>{throw Error('must not run');}}]);assert.equal(r.value,20);assert.deepEqual(calls,['chain','market']);assert.equal(r.attempts[0].httpStatus,530);});
test('batch RPC preserves request ordering and fails closed on missing/duplicated IDs and per-item errors',async()=>{const original=global.fetch;try{let response=[{id:2,result:'second'},{id:1,result:'first'}];global.fetch=async()=>({ok:true,json:async()=>response});const calls=[{method:'x',params:[]},{method:'y',params:[]}];assert.deepEqual(await c.batch(calls),['first','second']);response=[{id:1,result:'first'},{id:1,result:'other'}];await assert.rejects(c.batch(calls));response=[{id:1,error:{code:-1}},{id:2,result:'second'}];await assert.rejects(c.batch(calls));}finally{global.fetch=original;}});
test('legacy proxy detection requires actual slot opcode plus delegatecall, not constants hidden inside PUSH data',()=>{const slot=g.legacySlots.implementation.slice(2);assert.equal(g.isLegacy('0x7f'+slot+'f4'),true);assert.equal(g.isLegacy('0x7f'+slot+'00'),false);assert.equal(g.isLegacy('0x7ff4'+slot.slice(2)+'00'),false);});
test('generic verified ABI finds raw fee/burn/buyback candidates without guessing tax percentages or proving execution',async()=>{const original=c.call;try{c.call=async()=>word(250);const signatures=['buyTax()','burn(uint256)','buyback()'].map((signature,i)=>({signature,signatureHash4:'0x'+String(i+1).padStart(8,'0')}));const s={dataState:'DATA_FOUND',signatures:{function:signatures},abi:[{type:'function',name:'buyTax',inputs:[],outputs:[{type:'uint256'}]},{type:'function',name:'burn',inputs:[{type:'uint256'}],outputs:[]},{type:'function',name:'buyback',inputs:[],outputs:[]}]};const r=await g.inspect(token,s,'0x1');assert.equal(r.feeGetters.buyTax.value,'250');assert.equal(r.feeGetters.buyTax.status,'GETTER_REPORTED');assert.equal(r.burnMechanismCandidates[0].status,'CANDIDATE');assert.equal(r.buybackExecution.value,null);assert.equal(r.buybackMechanismCandidates.length,1);}finally{c.call=original;}});
test('metadata and unlock helpers reject private addresses, ticker identity and invalid/past dates',()=>{const m=require('../lib/project-metadata'),u=require('../lib/unlock-sources');for(const ip of ['127.0.0.1','10.0.0.1','169.254.169.254','192.168.1.1','::1','::ffff:127.0.0.1'])assert.equal(m.publicIP(ip),false);assert.equal(m.publicIP('8.8.8.8'),true);assert.equal(u.date('2020-01-01T00:00:00Z'),null);assert.equal(u.date('not-a-date'),null);assert.ok(u.date('2030-01-01T00:00:00Z'));});
test('source cache coalesces concurrent expensive calls',async()=>{f.clearCache();let calls=0;const read=async()=>{calls++;return 12;};assert.deepEqual(await Promise.all([f.cached('shared',10000,read),f.cached('shared',10000,read)]),[12,12]);assert.equal(calls,1);f.clearCache();});
