const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path'),{spawn}=require('node:child_process');
const storage=require('../lib/holder-storage'),c=require('../lib/core');
const a='0x'+'9'.repeat(40),name=a+'-candidates';
function execute(args,env){return new Promise((resolve,reject)=>{const child=spawn(process.execPath,args,{env,windowsHide:true});let output='';child.stdout.on('data',d=>output+=d);child.stderr.on('data',d=>output+=d);child.on('error',reject);child.on('exit',code=>code===0?resolve(output):reject(Error(output)));});}
test('cold Search reads only publications, never touches Redis or starts indexing',async()=>{
 const store=await require('./helpers/redis-rest.cjs').create(),previous={...process.env},original=[c.context,c.rpc,c.call];Object.assign(process.env,{ARC_INDEX_REDIS_URL:store.url,ARC_INDEX_REDIS_TOKEN:'test-only'});c.context=c.rpc=c.call=async()=>{throw Error('Forbidden request-driven RPC');};
 try{const r=await require('../api/holders')({method:'GET',query:{address:a}},{setHeader(){},status(){return this},json(d){return d;}});assert.equal(r.reasonCode,'HOLDER_PUBLICATION_UNAVAILABLE');assert.equal(r.publicationLookup.state,'FAILED');assert.equal(r.coverage.refreshQueued,false);for(const key of ['holderCount','largestWalletPct','top10Pct','top20Pct'])assert.equal(r[key],null);assert.deepEqual(store.commands,[]);assert.deepEqual(await storage.due(),[]);assert.equal(await storage.load(name),null);}finally{[c.context,c.rpc,c.call]=original;for(const k of ['ARC_INDEX_REDIS_URL','ARC_INDEX_REDIS_TOKEN'])if(previous[k]===undefined)delete process.env[k];else process.env[k]=previous[k];await store.close();}
});
test('separate persistent worker processes resume durable Redis cursors and publish only a pinned COMPLETE snapshot',async()=>{
 const store=await require('./helpers/redis-rest.cjs').create(),folder=await fs.mkdtemp(path.join(os.tmpdir(),'arcy-persistent-worker-')),preload=path.join(folder,'sources.cjs'),root=path.resolve(__dirname,'..'),env={...process.env,ARC_INDEX_REDIS_URL:store.url,ARC_INDEX_REDIS_TOKEN:'test-only'},holder='0x'+'1'.repeat(40);
 // Deterministic provider fixture. Redis protocol and worker run in separate real processes.
 await fs.writeFile(preload,`const c=require(${JSON.stringify(path.join(root,'lib/core'))}),r=require(${JSON.stringify(path.join(root,'lib/balance-reader'))}),old=c.json;c.json=async(u,o)=>u.startsWith('http://127.0.0.1:')?old(u,o):u.endsWith('/stats')?{chainId:5042,indexedBlocks:10}:u.includes('holders?')?{items:[{address:'${holder}'}],nextOffset:Number(new URL(u).searchParams.get('offset'))<50?Number(new URL(u).searchParams.get('offset'))+1:null}:{address:'${a}'};c.context=async()=>({block:'0xa'});c.call=async()=> '0x'+(1000n).toString(16).padStart(64,'0');c.rpc=async(m)=>m==='eth_chainId'?'0x13b2':m==='eth_getLogs'?[]:{hash:'0x'+'a'.repeat(64)};r.balances=async(t,addresses,b)=>({method:'pinned fixture',values:addresses.map(x=>'0x'+(x==='${holder}'?1000n:0n).toString(16).padStart(64,'0'))});`);
 try{store.queue.set(name,Date.now()-1);let output=await execute(['-r',preload,'scripts/holder-worker.cjs','--once'],env);assert.match(output,/BUILDING/);let document=JSON.parse(store.data.get('holders:v2:5042:'+name));assert.equal(document.checkpoint.offset,50);assert.equal(document.completedSnapshot,null);
 store.queue.set(name,Date.now()-1);output=await execute(['-r',preload,'scripts/holder-worker.cjs','--once'],env);assert.match(output,/COMPLETE/);document=JSON.parse(store.data.get('holders:v2:5042:'+name));assert.equal(document.checkpoint.phase,'COMPLETE');assert.equal(document.completedSnapshot.holderCount,1);assert.equal(document.completedSnapshot.block,'0xa');for(const field of Object.values(document.completedSnapshot.fields))assert.ok(field.evidence.some(e=>e.block==='0xa'));

 // Automatic loop: a genuinely cold queued job needs two slices; no caller requeues it.
 store.data.clear();store.queue.clear();store.queue.set(name,Date.now()-1);
 const loopOutput=await new Promise((resolve,reject)=>{const child=spawn(process.execPath,['-r',preload,'scripts/holder-worker.cjs'],{env,windowsHide:true});let output='';const timer=setTimeout(()=>{child.kill();reject(Error('Automatic continuation timeout'));},20000);child.stdout.on('data',d=>{output+=d;if(output.includes('"state":"COMPLETE"')){clearTimeout(timer);child.kill();resolve(output);}});child.on('error',reject);});
 assert.match(loopOutput,/"state":"BUILDING"/);assert.ok((loopOutput.match(/HOLDER_WORKER_BATCH/g)||[]).length>=2);assert.equal(JSON.parse(store.data.get('holders:v2:5042:'+name)).completedSnapshot.holderCount,1);
 const warm=await execute(['-e',`require('./lib/holder-display').cached('${a}').then(d=>console.log(JSON.stringify(d)))`],env);assert.equal(JSON.parse(warm).holderCount,1);assert.equal(JSON.parse(warm).snapshot.freshness,'LAST_VERIFIED');assert.equal(document.chainId,5042);assert.equal(document.contract,a);
 }finally{await store.close();await fs.rm(preload);await fs.rmdir(folder);}
});
test('persistent worker refuses ephemeral storage without emitting configuration values',async()=>{
 const env={...process.env};for(const k of ['ARC_INDEX_REDIS_URL','ARC_INDEX_REDIS_TOKEN','UPSTASH_REDIS_REST_URL','UPSTASH_REDIS_REST_TOKEN'])delete env[k];await assert.rejects(execute(['scripts/holder-worker.cjs','--once'],env),/Holder worker unavailable/);
});
