const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os'),worker=require('../lib/holder-candidates'),c=require('../lib/core');
const a='0x'+'c'.repeat(40),x='0x'+'a'.repeat(40),y='0x'+'b'.repeat(40),word=n=>'0x'+BigInt(n).toString(16).padStart(64,'0');
test('rate-limited discovery preserves its checkpoint and restart-like resume never exposes partial metrics',async()=>{
 const index=require('../lib/holder-index'),old=[index.load,index.save,c.json];let persisted={version:1,address:a,chainId:5042,phase:'DISCOVER',offset:100,addresses:[x],balances:[],balanceCursor:0},limited=true;
 try{index.load=async()=>structuredClone(persisted);index.save=async(_a,s)=>{persisted=structuredClone(s);};c.json=async url=>{if(url.endsWith('/stats'))return {chainId:5042,indexedBlocks:100};if(!url.includes('holders?'))return {address:a};assert.ok(url.endsWith('offset=100'));if(limited)throw Object.assign(Error('HTTP 429'),{httpStatus:429});return {items:[{address:y}],nextOffset:200};};
 await assert.rejects(worker.advance(a,{maxPages:1,maxBatches:0}),{httpStatus:429});assert.equal(persisted.offset,100);assert.deepEqual(persisted.addresses,[x]);limited=false;
 const r=await worker.advance(a,{maxPages:1,maxBatches:0});assert.equal(r.value,null);assert.equal(r.coverage.complete,false);assert.equal(persisted.offset,200);assert.deepEqual(persisted.addresses,[x,y]);
 }finally{[index.load,index.save,c.json]=old;}
});
test('expired holder snapshot starts fresh discovery without stale tail anchors or confidence',async()=>{
 const index=require('../lib/holder-index'),old=[index.load,index.save,c.json],saved=[];try{
 index.load=async()=>({version:1,address:a,chainId:5042,phase:'COMPLETE',completedAt:Date.now()-700000,startedAt:0,discoveryIndexedBlock:1,transferTail:{fromBlock:1},anchor:'old',block:'0x1',result:{holderCount:999},addresses:[x],balances:[[x,'999']],balanceCursor:1});index.save=async(_a,s)=>saved.push(structuredClone(s));c.json=async url=>url.includes('/stats')?{chainId:5042,indexedBlocks:100}:{address:a};const r=await worker.advance(a,{maxPages:0,maxBatches:0});assert.equal(r.value,null);assert.equal(r.coverage.phase,'DISCOVER');const s=saved.at(-1);assert.equal(s.discoveryIndexedBlock,100);assert.equal(s.anchor,undefined);assert.equal(s.result,undefined);assert.deepEqual(s.balances,[]);assert.deepEqual(s.addresses,[]);
 }finally{[index.load,index.save,c.json]=old;}
});
test('expired complete holder snapshots resume incremental Transfer discovery and re-read all balances at a new block',async()=>{
 const index=require('../lib/holder-index'),reader=require('../lib/balance-reader'),old=[index.load,index.save,c.context,c.rpc,c.call,reader.balances],saved=[],anchor='0x'+'1'.repeat(64);
 try{index.load=async()=>({version:1,address:a,chainId:5042,phase:'COMPLETE',completedAt:Date.now()-700000,block:'0x9',anchor,addresses:[x,...c.BURNS],balances:[[x,'1000']],result:{holderCount:1}});index.save=async(_a,s)=>saved.push(structuredClone(s));c.context=async()=>({block:'0xa'});c.call=async()=>word(1000);c.rpc=async(method,params)=>method==='eth_getBlockByNumber'?{hash:anchor}:[{address:a,blockNumber:'0xa',blockHash:anchor,logIndex:'0x0',topics:[index.TRANSFER,word(x),word(y)],data:word(400),removed:false}];reader.balances=async(_a,addresses,block)=>{assert.equal(block,'0xa');return {method:'test reconciliation',values:addresses.map(v=>word(v===x?600:v===y?400:0))};};const r=await worker.advance(a,{budgetMs:10000,maxPages:2,maxBatches:1});assert.equal(r.value.holderCount,2);assert.equal(r.value.largestWalletPct,60);assert.equal(r.value.block,'0xa');assert.equal(r.value.evidence[0].transferTail.fromBlock,10);assert.equal(saved.at(-1).phase,'COMPLETE');
 }finally{[index.load,index.save,c.context,c.rpc,c.call,reader.balances]=old;}
});
test('holder worker persists pagination and pinned balances, tolerates a stale count only after full supply reconciliation',async()=>{const original=global.fetch,old=process.env.ARC_INDEX_CACHE_DIR,folder=await fs.mkdtemp(path.join(os.tmpdir(),'arcy-worker-test-'));process.env.ARC_INDEX_CACHE_DIR=folder;const offsets=[];global.fetch=async(url,options)=>{let response;if(url.includes('/api/v1/stats'))response={chainId:5042};else if(url.includes('/holders?')){const offset=Number(new URL(url).searchParams.get('offset'));offsets.push(offset);response=offset===0?{items:[{address:x},{address:y}],total:3,nextOffset:2}:{items:[],total:3,nextOffset:2};}else if(url.includes('/api/v1/tokens/'))response={address:a};else{const payload=JSON.parse(options.body),one=r=>{let result;if(r.method==='eth_chainId')result='0x13b2';if(r.method==='eth_blockNumber')result='0xa';if(r.method==='eth_getCode')result='0x6000';if(r.method==='eth_getBlockByNumber')result={hash:'0x'+'1'.repeat(64)};if(r.method==='eth_call')result=r.params[0].data==='0x18160ddd'?word(1000):word(r.params[0].data.endsWith(x.slice(2))?600:r.params[0].data.endsWith(y.slice(2))?400:0);return {id:r.id,result};};response=Array.isArray(payload)?payload.map(one):one(payload);}return {ok:true,json:async()=>response};};try{const first=await worker.advance(a,{budgetMs:10000,maxPages:1,maxBatches:0});assert.equal(first.coverage.phase,'DISCOVER');assert.equal(first.coverage.candidateAddresses,2);const second=await worker.advance(a,{budgetMs:10000,maxPages:1,maxBatches:0});assert.equal(second.coverage.phase,'READ');assert.equal(second.coverage.balancesChecked,0);const third=await worker.advance(a,{budgetMs:10000,maxPages:1,maxBatches:1});assert.equal(third.value.holderCount,2);assert.equal(third.value.largestWalletPct,60);assert.equal(third.value.top20Pct,100);assert.equal(third.value.block,'0xa');assert.deepEqual(offsets,[0,2]);const cached=await worker.advance(a);assert.equal(cached.value.holderCount,2);assert.deepEqual(offsets,[0,2]);}finally{global.fetch=original;if(old===undefined)delete process.env.ARC_INDEX_CACHE_DIR;else process.env.ARC_INDEX_CACHE_DIR=old;const resolved=path.resolve(folder);if(resolved.startsWith(path.resolve(os.tmpdir())+path.sep)&&path.basename(resolved).startsWith('arcy-worker-test-'))await fs.rm(resolved,{recursive:true,force:true});}});
