const test=require('node:test'),assert=require('node:assert/strict'),{create}=require('../lib/holder-rpc'),budget=require('../lib/holder-budget');
function harness(handler){let clock=0;const calls=[];const client=create({endpoints:['primary','secondary'],now:()=>clock,sleep:async ms=>{clock+=ms;},interval:500,fetcher:async(url,options)=>{const p=JSON.parse(options.body);calls.push({url,p,at:clock});return handler(url,p,clock);}});return {client,calls,advance:ms=>{clock+=ms;}};}
const good=p=>({ok:true,json:async()=>Array.isArray(p)?p.map(x=>({id:x.id,result:'0x01'})):{id:p.id,result:p.method==='eth_chainId'?'0x13b2':'0x01'}});
test('429 quarantines primary, honors Retry-After, serves fallback without repeated hammering',async()=>{const h=harness((url,p)=>url==='primary'&&p.method!=='eth_chainId'?{ok:false,status:429,headers:new Headers({'retry-after':'60'})}:good(p));assert.equal(await h.client.rpc('eth_blockNumber',[]),'0x01');await h.client.rpc('eth_blockNumber',[]);assert.equal(h.calls.filter(x=>x.url==='primary'&&x.p.method!=='eth_chainId').length,1);assert.equal(h.client.metrics().http429,1);assert.equal(h.client.metrics().fallbacks,1);assert.equal(h.client.health()[0].limit,1);assert.ok(h.client.health()[0].cooldownMs>50000);h.advance(60001);await h.client.rpc('eth_blockNumber',[]);assert.equal(h.client.metrics().http429,2);});
test('HTTP 400 range rejection remains a range error for existing range shrinking',async()=>{const h=harness((url,p)=>p.method==='eth_getLogs'?{ok:false,status:400,headers:new Headers(),json:async()=>({error:{code:35,message:'ranges over 10000 blocks are not supported'}})}:good(p));await assert.rejects(h.client.rpc('eth_getLogs',[]),{code:'RPC_RANGE_LIMIT'});assert.equal(h.client.health()[0].cooldownMs,0);});
test('wrong-chain provider is excluded before any holder call',async()=>{const h=harness((url,p)=>url==='primary'?{ok:true,json:async()=>({id:p.id,result:'0x1'})}:good(p));assert.equal(await h.client.rpc('eth_blockNumber',[]),'0x01');assert.equal(h.calls.filter(x=>x.url==='primary').length,1);assert.equal(h.client.health()[0].cooldownMs,Infinity);});
test('timeout removes provider and a later healthy provider succeeds',async()=>{const h=harness((url,p)=>{if(url==='primary')throw Object.assign(Error(),{name:'TimeoutError'});return good(p);});assert.equal(await h.client.rpc('eth_blockNumber',[]),'0x01');assert.equal(h.client.metrics().errors,1);assert.equal(h.client.metrics().fallbacks,1);});
test('cooling providers yield to the worker deadline without sleeping past it',async()=>{const h=harness(()=>({ok:false,status:429,headers:new Headers({'retry-after':'60'})}));await assert.rejects(h.client.rpc('eth_blockNumber',[]));await assert.rejects(budget.run(20,()=>h.client.rpc('eth_blockNumber',[])),{code:'HOLDER_WORKER_BUDGET_EXHAUSTED'});assert.equal(h.calls.length,2);});
test('balance batches are bounded and preserve exact item ordering',async()=>{const h=harness((url,p)=>good(p));const values=await h.client.batch(Array.from({length:12},()=>({method:'eth_call',params:[]})));assert.equal(values.length,12);assert.deepEqual(h.calls.filter(x=>Array.isArray(x.p)).map(x=>x.p.length),[5,5,2]);assert.ok(h.client.metrics().backoffMs>0);});
test('a deadline-limited request yields its checkpoint slice without quarantining a healthy provider',async()=>{const client=create({endpoints:['healthy'],interval:0,fetcher:async(url,options)=>{const p=JSON.parse(options.body);if(p.method==='eth_chainId')return good(p);return new Promise((resolve,reject)=>options.signal.addEventListener('abort',()=>reject(Object.assign(Error(),{name:'TimeoutError'})),{once:true}));}});await assert.rejects(budget.run(30,()=>budget.operation(()=>client.rpc('eth_blockNumber',[]))),{code:'HOLDER_WORKER_BUDGET_EXHAUSTED'});await new Promise(r=>setTimeout(r,10));assert.equal(client.health()[0].cooldownMs,0);assert.equal(client.health()[0].interval,0);assert.equal(client.metrics().errors,0);assert.equal(client.metrics().http429,0);});
