const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os'),crypto=require('node:crypto');
const publication=require('../lib/holder-publication'),storage=require('../lib/holder-storage'),core=require('../lib/core');
const a='0x'+'7'.repeat(40),wallet='0x'+'1'.repeat(40),anchor='0x'+'a'.repeat(64);
function snapshot(block='0xa'){const s=require('../lib/holder-index').aggregate([[wallet,'100']],100n,[{block,anchor,source:'isolated pinned RPC fixture'}]);return {...s,block,snapshot:{block,completedAt:new Date().toISOString()}};}
async function fixture(fn){const dir=await fs.mkdtemp(path.join(os.tmpdir(),'arcy-publication-')),before={...process.env};process.env.ARC_HOLDER_PUBLISHED_DIR=path.join(dir,'published');process.env.ARC_INDEX_CACHE_DIR=path.join(dir,'index');process.env.ARC_HOLDER_STORAGE='local';try{await fn(dir);}finally{for(const k of Object.keys(process.env))if(!(k in before))delete process.env[k];Object.assign(process.env,before);if(path.resolve(dir).startsWith(path.resolve(os.tmpdir())+path.sep)&&path.basename(dir).startsWith('arcy-publication-'))await fs.rm(dir,{recursive:true,force:true});}}
const res={setHeader(){},status(){return this;},json(d){return d;}};
test('volume worker resumes a partial checkpoint in a fresh process and publishes only after reconciliation',()=>fixture(async dir=>{
 const root=path.resolve(__dirname,'..'),preload=path.join(dir,'provider.cjs'),env={...process.env};delete env.PORT;
 await fs.writeFile(preload,`const c=require(${JSON.stringify(path.join(root,'lib/core'))}),r=require(${JSON.stringify(path.join(root,'lib/balance-reader'))});c.json=async u=>u.endsWith('/stats')?{chainId:5042,indexedBlocks:10}:u.includes('holders?')?{items:[{address:'${wallet}'}],nextOffset:Number(new URL(u).searchParams.get('offset'))<50?Number(new URL(u).searchParams.get('offset'))+1:null}:{address:'${a}'};c.context=async()=>({block:'0xa'});c.call=async()=> '0x'+(100n).toString(16).padStart(64,'0');c.rpc=async m=>m==='eth_chainId'?'0x13b2':m==='eth_getLogs'?[]:{hash:'${anchor}'};r.balances=async(t,addresses,b)=>({method:'isolated pinned fixture',values:addresses.map(x=>'0x'+(x==='${wallet}'?100n:0n).toString(16).padStart(64,'0'))});`);
 await storage.enqueue(a);const exec=require('node:child_process').execFileSync;
 const first=exec(process.execPath,['-r',preload,'scripts/holder-worker.cjs','--once'],{cwd:root,env,windowsHide:true,encoding:'utf8'});assert.match(first,/BUILDING/);assert.equal((await storage.load(a+'-candidates')).offset,50);assert.equal(await publication.read(a),null);
 await storage.enqueue(a,Date.now()-1,true);
 const second=exec(process.execPath,['-r',preload,'scripts/holder-worker.cjs','--once'],{cwd:root,env,windowsHide:true,encoding:'utf8'});assert.match(second,/COMPLETE/);const s=await publication.read(a);assert.equal(s.holderCount,1);assert.equal(s.block,'0xa');assert.equal((await storage.load(a+'-candidates')).balanceCursor,3);for(const f of Object.values(s.fields))assert.ok(f.evidence.some(e=>e.block===s.block));
}));
test('separate authenticated queue request persists one job and publishes signed COMPLETE independently',()=>fixture(async()=>{
 process.env.PORT='0';process.env.ARC_HOLDER_QUEUE_TOKEN='isolated-test-only';process.env.ARC_HOLDER_QUEUE_URL='https://worker.example/queue';
 const pair=crypto.generateKeyPairSync('ed25519');process.env.ARC_HOLDER_SIGNING_KEY=pair.privateKey.export({type:'pkcs8',format:'pem'});process.env.ARC_HOLDER_PUBLIC_KEY=pair.publicKey.export({type:'spki',format:'pem'});process.env.ARC_HOLDER_PUBLISHED_URL='https://worker.example/snapshots/';
 const server=require('../lib/holder-worker-http').start();await new Promise(r=>server.listening?r():server.once('listening',r));const base='http://127.0.0.1:'+server.address().port,original=global.fetch;
 try{const wrong=await original(base+'/queue',{method:'POST',body:'{}'});assert.equal(wrong.status,401);
  global.fetch=(url,options)=>original(base+new URL(url).pathname,options);
  const queue=require('../lib/holder-queue-client');const results=await Promise.all([queue.enqueue(a),queue.enqueue(a)]);assert.ok(results.every(d=>d.queued));assert.deepEqual(await storage.due(),[a]);
  assert.equal(await publication.remote(a),null);await publication.publish(a,snapshot());assert.equal((await publication.remote(a)).top10Pct,100);
  // A later publication failure cannot destroy the already available COMPLETE file.
  await assert.rejects(publication.publish(a,{...snapshot(),coverage:{complete:false}}));assert.equal((await publication.remote(a)).holderCount,1);
 }finally{global.fetch=original;await new Promise(r=>server.close(r));}
}));
test('cold initial holder response makes zero network, Redis, queue or discovery calls',()=>fixture(async()=>{const old=[storage.snapshot,storage.enqueue,core.json,core.rpc];storage.snapshot=storage.enqueue=core.json=core.rpc=()=>{throw Error('Forbidden critical-path dependency');};try{const start=performance.now(),d=await require('../api/holders')({query:{address:a}},res);assert.equal(d.reasonCode,'HOLDER_SNAPSHOT_NOT_PUBLISHED');assert.equal(d.coverage.refreshQueued,false);assert.ok(performance.now()-start<100);for(const k of ['holderCount','largestWalletPct','top10Pct','top20Pct'])assert.equal(d.fields[k].value,null);}finally{[storage.snapshot,storage.enqueue,core.json,core.rpc]=old;}}));
test('atomic publication rejects partial/regressed snapshots and fresh processes load COMPLETE without Redis',()=>fixture(async()=>{await publication.publish(a,snapshot());await assert.rejects(publication.publish(a,{...snapshot(),coverage:{complete:false}}));await assert.rejects(publication.publish(a,snapshot('0x9')));const output=require('node:child_process').execFileSync(process.execPath,['-e',`require('./lib/holder-publication').read('${a}').then(d=>console.log(JSON.stringify(d)))`],{cwd:path.resolve(__dirname,'..'),env:process.env,windowsHide:true,encoding:'utf8'});const d=JSON.parse(output);assert.equal(d.holderCount,1);assert.equal(d.block,'0xa');assert.equal(d.top20Pct,100);assert.equal((await publication.read(a)).block,'0xa');}));
test('independent remote publication requires a valid signature, exact contract and COMPLETE evidence',()=>fixture(async()=>{const pair=crypto.generateKeyPairSync('ed25519');process.env.ARC_HOLDER_SIGNING_KEY=pair.privateKey.export({type:'pkcs8',format:'pem'});process.env.ARC_HOLDER_PUBLIC_KEY=pair.publicKey.export({type:'spki',format:'pem'});process.env.ARC_HOLDER_PUBLISHED_URL='https://publications.example/5042/';await publication.publish(a,snapshot());const d=JSON.parse(await fs.readFile(path.join(publication.directory(),a+'.json'))),original=global.fetch;try{global.fetch=async()=>({ok:true,json:async()=>d});assert.equal((await publication.remote(a)).holderCount,1);assert.equal(await publication.remote(wallet),null);d.payload=d.payload.replace('"holderCount":1','"holderCount":2');assert.equal(await publication.remote(a),null);}finally{global.fetch=original;}}));
test('persistent volume queue survives separate execution and deduplicates without touching configured Redis',()=>fixture(async()=>{process.env.ARC_INDEX_REDIS_URL='https://unavailable.example';process.env.ARC_INDEX_REDIS_TOKEN='isolated-test-only';assert.equal(storage.mode(),'local');await storage.enqueue(a);await storage.enqueue(a);const output=require('node:child_process').execFileSync(process.execPath,['-e',"require('./lib/holder-storage').due(5).then(d=>console.log(JSON.stringify(d)))"],{cwd:path.resolve(__dirname,'..'),env:process.env,windowsHide:true,encoding:'utf8'});assert.deepEqual(JSON.parse(output),[a]);}));
test('liquidity summary returns exact-contract market data while LP evidence is slow or unavailable',async()=>{const identity=require('../lib/token-identity'),market=require('../lib/market-activity'),lp=require('../lib/lp-status'),old=[identity.inspect,market.dexPairs,lp.inspect];require('../lib/fields').clearCache();identity.inspect=async()=>({address:a,chainId:5042});market.dexPairs=async()=>[{chainId:'arc',dexId:'test',pairAddress:wallet,baseToken:{address:a},quoteToken:{address:wallet},liquidity:{usd:100},volume:{h24:20}}];lp.inspect=()=>{throw Error('Summary must not run LP analysis');};try{const d=await require('../api/liquidity')({query:{address:a,summary:'1'}},res);assert.equal(d.liquidityUsd,100);assert.equal(d.volume24h,20);assert.equal(d.fields.liquidityUsd.dataState,'DATA_FOUND');assert.equal(d.lpStatus.value,null);assert.equal(d.lpStatus.reasonCode,'LP_EVIDENCE_PENDING');}finally{[identity.inspect,market.dexPairs,lp.inspect]=old;require('../lib/fields').clearCache();}});
test('LP background detail reuses this scan summary without duplicate identity/market calls and a new scan refreshes',async()=>{const identity=require('../lib/token-identity'),market=require('../lib/market-activity'),lp=require('../lib/lp-status'),old=[identity.inspect,market.dexPairs,lp.inspect];let reads=0;const f=require('../lib/fields');f.clearCache();identity.inspect=async()=>{reads++;return {address:a,chainId:5042};};market.dexPairs=async()=>[{chainId:'arc',dexId:'test',pairAddress:wallet,baseToken:{address:a},quoteToken:{address:wallet},liquidity:{usd:100},volume:{h24:20}}];lp.inspect=async()=>core.fact('UNLOCKED',[{block:'0xa'}]);try{const api=require('../api/liquidity'),query={address:a,refresh:'1',scanId:'isolated-scan'};const summary=await api({query:{...query,summary:'1'}},res),detail=await api({query:{...query,details:'1'}},res);assert.equal(reads,1);assert.equal(summary.lpStatus.value,null);assert.equal(detail.lpStatus.value,'UNLOCKED');assert.equal(detail.liquidityUsd,summary.liquidityUsd);await api({query:{...query,summary:'1',scanId:'another-scan'}},res);assert.equal(reads,2);}finally{[identity.inspect,market.dexPairs,lp.inspect]=old;f.clearCache();}});
