const test=require('node:test'),assert=require('node:assert/strict'),c=require('../lib/core'),s=require('../lib/verified-source'),hook=require('../lib/mechanics-hook'),keccak=require('../lib/keccak');
const a='0x'+'1'.repeat(40),portal='0x'+'2'.repeat(40),manager='0x'+'3'.repeat(40),quote='0x'+'4'.repeat(40),h='0x'+'5'.repeat(40),splitter='0x'+'6'.repeat(40),block='0x123';
const w=x=>'0x'+BigInt(x).toString(16).padStart(64,'0'),addr=x=>'0x'+x.slice(2).padStart(64,'0'),selector=x=>keccak(Buffer.from(x)).slice(0,10),profile={profile:{id:'ARGUS_V4_LAUNCH_TOKEN_7'},sourceDigest:'f4abba6aa7071125168a9b9ea39cdfd08f01835d3c59aa74c55173c71e50daa1'};
async function fixture(change,fn){const original=[c.rpc,c.call,c.batch,s.lookup];const values={token:addr(a),portal:addr(portal),poolManager:addr(manager),quoteAsset:addr(quote),splitter:addr(splitter),buyTaxBps:w(300),sellTaxBps:w(500),currentSnipeTaxBps:w(0),poolFee:w(10000),tickSpacing:w(200)};values.poolId=keccak(Buffer.from([addr(a),addr(quote),values.poolFee,values.tickSpacing,addr(h)].map(x=>x.slice(2)).join(''),'hex'));change(values);const signatures=Object.keys(values).map(n=>({signature:n+'()',signatureHash4:selector(n+'()')}));try{c.rpc=async()=> '0x6000';s.lookup=async address=>({dataState:'DATA_FOUND',runtimeMatch:'exact_match',sourceDigest:address===portal?hook.reviewed.portal:hook.reviewed.hook,signatures:{function:address===portal?[{signature:'launches(address)',signatureHash4:selector('launches(address)')}]:signatures}});c.call=async(address,data,b)=>{assert.equal(b,block);if(address===a)return addr(({[selector('portal()')]:portal,[selector('poolManager()')]:manager,[selector('quoteAsset()')]:quote})[data]);return '0x'+[addr(a),w(0),w(1),addr(splitter),addr(h),addr(splitter),w(300),w(500),w(1),w(0),addr(quote)].map(x=>x.slice(2)).join('');};c.batch=async calls=>calls.map(x=>{assert.equal(x.params[1],block);assert.equal(x.params[0].to,h);return values[signatures.find(y=>y.signatureHash4===x.params[0].data).signature.split('(')[0]];});await fn();}finally{[c.rpc,c.call,c.batch,s.lookup]=original;}}
test('reviewed hook rates require exact token/portal/quote/pool binding at one pinned block',async()=>fixture(()=>{},async()=>{const result=await hook.inspect(a,block,profile);assert.equal(result.buyTax.value,3);assert.equal(result.sellTax.value,5);assert.equal(result.buyTax.evidence[0].block,block);assert.equal(result.buyTax.evidence[0].lpFeeMillionths,'10000');assert.match(result.buyTax.scope,/not an all-pool/);}));
test('reviewed anti-sniping surcharge is read and capped per direction, LP fee never mislabeled as tax',async()=>fixture(v=>v.currentSnipeTaxBps=w(9800),async()=>{const result=await hook.inspect(a,block,profile);assert.equal(result.buyTax.value,99);assert.equal(result.sellTax.value,99);assert.equal(result.buyTax.basePercent,3);assert.equal(result.buyTax.antiSnipePercent,96);}));
test('wrong contract binding, pool ID and inconsistent rates cannot be published',async()=>{for(const change of [v=>v.token=addr(quote),v=>v.poolId=w(1),v=>v.buyTaxBps=w(301)])await fixture(change,async()=>assert.rejects(hook.inspect(a,block,profile)));});
test('unreviewed runtime/source or ABI cannot establish hook tax',async()=>{assert.equal(hook.matched({dataState:'DATA_FOUND',runtimeMatch:'EXPLORER_ATTESTATION',sourceDigest:hook.reviewed.hook},hook.reviewed.hook),false);assert.equal(hook.matched({dataState:'DATA_FOUND',runtimeMatch:'exact_match',sourceDigest:'other'},hook.reviewed.hook),false);await assert.rejects(hook.inspect(a,block,{...profile,sourceDigest:'other'}));});
test('compiler template accepts only immutable substitutions; altered instructions, metadata and inconsistent copies fail',()=>{const t=require('../lib/mechanics-hook-template.json'),b=Buffer.from(t.runtimeBytecode.slice(2),'hex');for(const ranges of Object.values(t.immutableReferences))for(const r of ranges)b.fill(7,r.start,r.start+r.length);const code='0x'+b.toString('hex');assert.equal(hook.templateMatch(code),true);const changed=Buffer.from(b);changed[0]^=1;assert.equal(hook.templateMatch('0x'+changed.toString('hex')),false);const metadata=Buffer.from(b);metadata[metadata.length-3]^=1;assert.equal(hook.templateMatch('0x'+metadata.toString('hex')),false);const inconsistent=Buffer.from(b);inconsistent[Object.values(t.immutableReferences)[0][0].start]^=1;assert.equal(hook.templateMatch('0x'+inconsistent.toString('hex')),false);assert.equal(hook.templateMatch(code+'00'),false);});
