const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto');
const storage=require('../lib/pulse-storage'),client=require('../lib/pulse-client'),pulse=require('../lib/pulse-edition');
const source='https://arc.network/blog/example';
function edition(n=2){return {schemaVersion:1,number:n,generatedAt:'2026-10-05T06:00:00.000Z',trigger:'cron',success:true,status:'updated',cycle:{start:'2026-10-05T00:00:00.000Z',end:'2026-10-12T00:00:00.000Z'},cards:[{owner:'OFFICIAL ARC',publishedAt:'2026-10-05T01:00:00.000Z',kind:'week',title:'Arc update',summary:'Verified update.',url:source},{owner:'SOURCE COVERAGE',publishedAt:'2026-10-05T06:00:00.000Z',kind:'new',title:'No additional verified development.',summary:'No stale announcement was reused.',url:''},{owner:'NEXT REVIEW',publishedAt:'2026-10-05T06:00:00.000Z',kind:'watch',title:'Weekly source review continues.',summary:'The next source review is scheduled.',url:''}],take:'This week’s verified Arc signal: Arc update.',sources:[source],audit:{acceptedItemCount:1,rejected:{stale:0,duplicate:0,undated:0},sourcesChecked:[]}};}
async function fixture(fn){const dir=await fs.mkdtemp(path.join(os.tmpdir(),'arcy-pulse-')),before={...process.env},pair=crypto.generateKeyPairSync('ed25519');process.env.ARC_HOLDER_PUBLISHED_DIR=path.join(dir,'published');process.env.ARC_HOLDER_SIGNING_KEY=pair.privateKey.export({type:'pkcs8',format:'pem'});process.env.ARC_HOLDER_PUBLIC_KEY=pair.publicKey.export({type:'spki',format:'pem'});try{await fn(dir);}finally{for(const key of Object.keys(process.env))if(!(key in before))delete process.env[key];Object.assign(process.env,before);await fs.rm(dir,{recursive:true,force:true});}}
function res(){return {headers:{},setHeader(k,v){this.headers[k]=v;},status(code){this.code=code;return this;},json(body){this.body=body;return this;}};}

test('Pulse editions are signed, atomically retained and a failed refresh keeps the prior weekly edition',()=>fixture(async()=>{
 await storage.publish(edition());const initial=await storage.latest();assert.equal(initial.number,2);await storage.failure(Object.assign(Error(),{code:'PULSE_SOURCE_FAILURE'}),Date.parse('2026-10-12T06:00:00Z'));
 assert.equal((await storage.latest()).number,2);const audit=await storage.audit();assert.equal(audit.lastSuccessful.number,2);assert.equal(audit.lastFailure.code,'PULSE_SOURCE_FAILURE');assert.equal(audit.lastFailure.status,'failed');
}));
test('normal Pulse reads only the saved edition; authenticated cron/manual refresh is the only publisher path',()=>fixture(async()=>{
 const handler=require('../api/pulse'),old=[client.latest,client.refresh,client.audit],saved=edition();let refreshes=0;client.latest=async()=>saved;client.audit=async()=>({lastSuccessful:{number:2},lastFailure:null});client.refresh=async trigger=>{refreshes++;return {ok:true,edition:{...saved,trigger}};};process.env.CRON_SECRET='test-secret';
 try{let r=res();await handler({method:'GET',headers:{},query:{}},r);assert.equal(r.code,200);assert.equal(r.body.cards[0].title,'Arc update');assert.equal(refreshes,0);r=res();await handler({method:'POST',headers:{},query:{}},r);assert.equal(r.code,401);r=res();await handler({method:'GET',headers:{authorization:'Bearer test-secret','x-vercel-cron':'1'},query:{}},r);assert.equal(r.code,200);assert.equal(refreshes,1);assert.equal(r.body.audit.lastSuccessful.number,2);}finally{[client.latest,client.refresh,client.audit]=old;delete process.env.CRON_SECRET;}
}));
test('worker refresh endpoint persists a signed edition and makes the same edition available to readers',()=>fixture(async()=>{
 const oldGenerate=pulse.generate,serverModule=require('../lib/holder-worker-http'),quiet={...edition(),status:'quiet_week',cards:pulse.quietCards(Date.parse('2026-10-05T06:00:00Z'))};pulse.generate=async({trigger})=>({...quiet,trigger});process.env.PORT='0';process.env.ARC_HOLDER_QUEUE_TOKEN='test-worker-token';const server=serverModule.start();await new Promise(resolve=>server.listening?resolve():server.once('listening',resolve));const base='http://127.0.0.1:'+server.address().port;
 try{let r=await fetch(base+'/pulse/refresh',{method:'POST',headers:{authorization:'Bearer test-worker-token','content-type':'application/json'},body:JSON.stringify({trigger:'cron'})});assert.equal(r.status,200);assert.equal((await r.json()).ok,true);r=await fetch(base+'/pulse/latest');assert.equal(r.status,200);const envelope=await r.json();assert.equal(storage.unpack(envelope).number,2);assert.equal(storage.unpack(envelope).status,'quiet_week');r=await fetch(base+'/pulse/audit',{headers:{authorization:'Bearer test-worker-token'}});assert.equal(r.status,200);assert.equal((await r.json()).lastSuccessful.trigger,'cron');assert.equal((await storage.audit()).lastSuccessful.status,'quiet_week');}finally{pulse.generate=oldGenerate;await new Promise(resolve=>server.close(resolve));delete process.env.PORT;delete process.env.ARC_HOLDER_QUEUE_TOKEN;}
}));
test('a storage failure records a failed audit without replacing the prior successful edition',()=>fixture(async()=>{
 const oldGenerate=pulse.generate,oldPublish=storage.publish,serverModule=require('../lib/holder-worker-http');process.env.PORT='0';process.env.ARC_HOLDER_QUEUE_TOKEN='test-worker-token';
 await storage.publish(edition());pulse.generate=async()=>({...edition(3),number:3});storage.publish=async()=>{throw Object.assign(Error('write failed'),{code:'PULSE_STORAGE_FAILURE'});};const server=serverModule.start();await new Promise(resolve=>server.listening?resolve():server.once('listening',resolve));const base='http://127.0.0.1:'+server.address().port;
 try{const r=await fetch(base+'/pulse/refresh',{method:'POST',headers:{authorization:'Bearer test-worker-token','content-type':'application/json'},body:'{}'});assert.equal(r.status,503);assert.equal((await storage.latest()).number,2);const audit=await storage.audit();assert.equal(audit.lastFailure.status,'failed');assert.equal(audit.lastFailure.code,'PULSE_STORAGE_FAILURE');}finally{pulse.generate=oldGenerate;storage.publish=oldPublish;await new Promise(resolve=>server.close(resolve));delete process.env.PORT;delete process.env.ARC_HOLDER_QUEUE_TOKEN;}
}));
test('Pulse reads its signed edition from the publication host but sends refresh only to the authenticated queue host',()=>fixture(async()=>{
 const pair=crypto.generateKeyPairSync('ed25519'),oldFetch=global.fetch,old={published:process.env.ARC_HOLDER_PUBLISHED_URL,queue:process.env.ARC_HOLDER_QUEUE_URL,token:process.env.ARC_HOLDER_QUEUE_TOKEN,key:process.env.ARC_HOLDER_PUBLIC_KEY};process.env.ARC_HOLDER_PUBLIC_KEY=pair.publicKey.export({type:'spki',format:'pem'});process.env.ARC_HOLDER_PUBLISHED_URL='https://published.example/snapshots/';process.env.ARC_HOLDER_QUEUE_URL='https://queue.example/queue';process.env.ARC_HOLDER_QUEUE_TOKEN='queue-token';const payload=JSON.stringify(edition()),signed={payload,signature:crypto.sign(null,Buffer.from(payload),pair.privateKey).toString('base64')},calls=[];
 global.fetch=async(url,options={})=>{calls.push({url:String(url),options});return String(url).includes('/pulse/latest')?{ok:true,json:async()=>signed}:{ok:true,json:async()=>({ok:true,edition:signed})};};try{assert.equal((await client.latest()).number,2);assert.equal((await client.refresh('cron')).ok,true);assert.match(calls[0].url,/published\.example\/pulse\/latest/);assert.match(calls[1].url,/queue\.example\/pulse\/refresh/);}finally{global.fetch=oldFetch;for(const [key,value] of Object.entries(old)){const name={published:'ARC_HOLDER_PUBLISHED_URL',queue:'ARC_HOLDER_QUEUE_URL',token:'ARC_HOLDER_QUEUE_TOKEN',key:'ARC_HOLDER_PUBLIC_KEY'}[key];if(value===undefined)delete process.env[name];else process.env[name]=value;}}
}));
