'use strict';
const model=window.ARCYModel,$=id=>document.getElementById(id),input=$('contract'),scan=$('scan'),cards={};
const holderViews=new Map();
const routeViews=new Map();let scanSequence=0,scanController;
function lastData(d,state){const value=structuredClone(d);value.freshness={...value.freshness,state:'LAST_VERIFIED',observedAt:value.freshness?.observedAt||value.scannedAt,refresh:state};return value;}
function sourceFailed(route,d){const name=['supply','market','unlock'].includes(route)?'supply':route;const fields=model.summarize(name,name==='supply'?{[route]:d}:d).fields;return fields.some(f=>f.dataState==='SOURCE_API_FAILED')&&!fields.some(f=>['DATA_FOUND','FRONTEND_MAPPING_FAILED'].includes(f.dataState));}
function useful(route,d){if(d?.ok!==true)return false;const name=['supply','market','unlock'].includes(route)?'supply':route;return model.summarize(name,name==='supply'?{[route]:d}:d).fields.some(f=>f.dataState==='DATA_FOUND');}
function progress(views,pending){const fields=Object.values(views).flatMap(x=>x.fields),found=fields.filter(x=>x.dataState==='DATA_FOUND').length,mappingFailed=fields.some(x=>x.dataState==='FRONTEND_MAPPING_FAILED');$('scanStatus').textContent=mappingFailed?'DATA MAPPING FAILED':pending?'SCANNING':found?'PARTIAL EVIDENCE':'NO VERIFIED RESULTS';$('helper').textContent=found+' of '+Object.values(model.labels).reduce((n,x)=>n+x.length,0)+' summary fields have evidence. Open View Evidence for source failures, missing data and verification limits.';scan.dataset.pending=String(pending);}
function completeHolders(d,a){return d?.ok===true&&d.address?.toLowerCase()===a.toLowerCase()&&d.chainId===5042&&d.coverage?.complete===true&&d.status==='ONCHAIN_VERIFIED'&&d.snapshot?.block===d.block&&['holderCount','largestWalletPct','top10Pct','top20Pct'].every(k=>d.fields?.[k]?.dataState==='DATA_FOUND'&&d.fields[k].value===d[k]);}
function lastHolders(d,state){const value=structuredClone(d);value.snapshot={...value.snapshot,freshness:'LAST_VERIFIED',refresh:{state}};return value;}
for(const [name,labels]of Object.entries(model.labels)){const card=document.querySelector('.card.'+name);card.querySelectorAll('.row,.badge,.details').forEach(x=>x.remove());if(name==='claims'){card.setAttribute('translate','no');card.classList.add('notranslate');}const rowHost=card;const values=labels.map(label=>{const row=document.createElement('div');row.className='row';const span=document.createElement('span');span.textContent=label;const b=document.createElement('b');b.textContent='—';row.append(span,b);rowHost.append(row);return b;});const badge=document.createElement('div');badge.className='badge';badge.textContent='NOT SCANNED';badge.setAttribute('translate','no');const details=document.createElement('details'),summary=document.createElement('summary'),pre=document.createElement('pre');summary.textContent='View Evidence';pre.setAttribute('translate','no');details.append(summary,pre);card.append(badge,details);cards[name]={card,values,badge,pre};}
function render(name,data){const view=model.summarize(name,data),card=cards[name];card.values.forEach((b,i)=>{const f=view.fields[i];b.textContent=f.text;b.dataset.dataState=f.dataState;b.title=f.reason||'';b.setAttribute('translate','no');});card.badge.textContent=view.badge;card.pre.textContent=JSON.stringify({fieldAudit:view.fields,response:data},null,2);card.card.dataset.mappingState=view.fields.some(x=>x.dataState==='FRONTEND_MAPPING_FAILED')?'FAILED':'OK';return view;}
async function request(route,a,signal,scanId){const controller=new AbortController(),abort=()=>controller.abort(),timer=setTimeout(abort,55000);if(signal.aborted)abort();else signal.addEventListener('abort',abort,{once:true});try{const r=await fetch('/api/'+route+'?address='+encodeURIComponent(a)+(route==='holders'?'':'&refresh=1&scanId='+encodeURIComponent(scanId)),{signal:controller.signal,cache:'no-store'});if(!r.ok)return {ok:false,dataState:'SOURCE_API_FAILED',reasonCode:'APPLICATION_HTTP_ERROR',httpStatus:r.status,reason:'Application endpoint failed.'};let d;try{d=await r.json();}catch{return {ok:false,dataState:'SOURCE_API_FAILED',reasonCode:'APPLICATION_MALFORMED_JSON',reason:'Application endpoint did not return JSON.'};}if(!d||typeof d!=='object'||typeof d.ok!=='boolean')return {ok:true,dataState:'FRONTEND_MAPPING_FAILED',reasonCode:'APPLICATION_SCHEMA_MISMATCH',reason:'Application response schema is invalid.'};if(d.ok&&(typeof d.address!=='string'||d.address.toLowerCase()!==a.toLowerCase()||d.chainId!==5042))return {ok:false,dataState:'FRONTEND_MAPPING_FAILED',reasonCode:'APPLICATION_IDENTITY_MISMATCH',reason:'Response contract or chain does not match this Search.'};return d;}catch{return {ok:false,dataState:'SOURCE_API_FAILED',reasonCode:'APPLICATION_REQUEST_FAILED',reason:'Application request failed or timed out.'};}finally{clearTimeout(timer);signal.removeEventListener('abort',abort);}}
async function startScan(){if(scan.disabled)return;const a=input.value.trim();if(!/^0x[0-9a-f]{40}$/i.test(a)){$('helper').textContent='Enter a valid contract address.';return;}const sequence=++scanSequence,scanId=crypto.randomUUID();scanController?.abort();scanController=new AbortController();const signal=scanController.signal,key=a.toLowerCase(),old=routeViews.get(key)||{},supply={},views={};let pending=8;scan.disabled=true;$('token').classList.add('show');$('address').textContent=a;$('tokenName').textContent='Token scan';$('tokenMeta').textContent='';$('scanStatus').textContent='SCANNING';for(const route of ['supply','market','unlock'])if(old[route])supply[route]=lastData(old[route],'REQUESTING');for(const name of Object.keys(cards))views[name]=render(name,name==='whales'&&holderViews.has(key)?lastHolders(holderViews.get(key),'REQUESTING'):name==='supply'?supply:old[name]?lastData(old[name],'REQUESTING'):undefined);progress(views,pending);
const jobs=['token','supply','market','unlock','holders','liquidity','activity','mechanics'].map(async route=>{const d=await request(route,a,signal,scanId);if(sequence!==scanSequence)return;pending--;if(route==='token'){if(d.ok&&d.token){$('tokenName').textContent=(d.token.name||'Token')+(d.token.symbol?' ('+d.token.symbol+')':'');$('tokenMeta').textContent='Arc · Chain 5042 · Decimals: '+d.token.decimals;}else $('tokenMeta').textContent='Token metadata unavailable.';}else{
let data=d;if(route!=='holders'){if((d.ok===false||d.dataState==='SOURCE_API_FAILED'||sourceFailed(route,d))&&d.dataState!=='FRONTEND_MAPPING_FAILED'&&old[route]){data=lastData(old[route],'FAILED');data.refreshFailure=d;}else if(route==='supply'&&d.ok&&d.burnAddressBalance?.amount===null&&old.supply?.burnAddressBalance?.amount!==null&&old.supply?.burnAddressBalance){data=structuredClone(d);const previous=lastData(old.supply,'FAILED');data.burnAddressBalance={...previous.burnAddressBalance,freshness:previous.freshness,refreshFailure:d.burnAddressBalance};data.fields.burnAddressBalance={...previous.fields.burnAddressBalance,freshness:previous.freshness};}if(d.ok&&old[route]&&!['supply','market','unlock'].includes(route)){for(const [field,value]of Object.entries(d)){if(value?.value===null&&value.dataState==='SOURCE_API_FAILED'&&old[route][field]?.value!==null&&old[route][field]?.value!==undefined){if(data===d)data=structuredClone(d);const previous=lastData(old[route],'FAILED');data[field]={...previous[field],freshness:previous.freshness,refreshFailure:value};if(data.fields?.[field])data.fields[field]=data[field];}}}if(useful(route,data)&&d.ok===true&&d.address?.toLowerCase()===key&&d.chainId===5042){const retained={...old,[route]:data};routeViews.set(key,retained);Object.assign(old,retained);if(routeViews.size>20)routeViews.delete(routeViews.keys().next().value);}}
if(['supply','market','unlock'].includes(route)){supply[route]=data;views.supply=render('supply',supply);}else{const name=route==='holders'?'whales':route;if(route==='holders'){if(d.reasonCode==='HOLDER_SNAPSHOT_ANCHOR_CHANGED')holderViews.delete(key);if(completeHolders(d,a)){holderViews.set(key,d);if(holderViews.size>20)holderViews.delete(holderViews.keys().next().value);}else if(holderViews.has(key))data=lastHolders(holderViews.get(key),d.ok===false?'FAILED':'BUILDING');}views[name]=render(name,data);}}
progress(views,pending);scan.disabled=false;});
await Promise.allSettled(jobs);if(sequence!==scanSequence)return;progress(views,0);scan.disabled=false;}
scan.addEventListener('click',startScan);input.addEventListener('keydown',e=>{if(e.key==='Enter')startScan();});
input.addEventListener('input',()=>{scan.disabled=false;});
