'use strict';
const model=window.ARCYModel,$=id=>document.getElementById(id),input=$('contract'),scan=$('scan'),cards={};
for(const [name,labels]of Object.entries(model.labels)){const card=document.querySelector('.card.'+name);card.querySelectorAll('.row,.badge,.details').forEach(x=>x.remove());if(name==='claims'){card.setAttribute('translate','no');card.classList.add('notranslate');}const values=labels.map(label=>{const row=document.createElement('div');row.className='row';const span=document.createElement('span');span.textContent=label;const b=document.createElement('b');b.textContent='—';row.append(span,b);card.append(row);return b;});const badge=document.createElement('div');badge.className='badge';badge.textContent='NOT SCANNED';badge.setAttribute('translate','no');const details=document.createElement('details'),summary=document.createElement('summary'),pre=document.createElement('pre');summary.textContent='View Evidence';pre.setAttribute('translate','no');details.append(summary,pre);card.append(badge,details);cards[name]={card,values,badge,pre};}
function render(name,data){const view=model.summarize(name,data),card=cards[name];card.values.forEach((b,i)=>{const f=view.fields[i];b.textContent=f.text;b.dataset.dataState=f.dataState;b.title=f.reason||'';b.setAttribute('translate','no');});card.badge.textContent=view.badge;card.pre.textContent=JSON.stringify({fieldAudit:view.fields,response:data},null,2);card.card.dataset.mappingState=view.fields.some(x=>x.dataState==='FRONTEND_MAPPING_FAILED')?'FAILED':'OK';return view;}
async function request(route,a){try{const r=await fetch('/api/'+route+'?address='+encodeURIComponent(a),{signal:AbortSignal.timeout(55000),cache:'no-store'});if(!r.ok)return {ok:false,dataState:'SOURCE_API_FAILED',reasonCode:'APPLICATION_HTTP_ERROR',httpStatus:r.status,reason:'Application endpoint failed.'};let d;try{d=await r.json();}catch{return {ok:false,dataState:'SOURCE_API_FAILED',reasonCode:'APPLICATION_MALFORMED_JSON',reason:'Application endpoint did not return JSON.'};}if(!d||typeof d!=='object'||typeof d.ok!=='boolean')return {ok:true,dataState:'FRONTEND_MAPPING_FAILED',reasonCode:'APPLICATION_SCHEMA_MISMATCH',reason:'Application response schema is invalid.'};return d;}catch{return {ok:false,dataState:'SOURCE_API_FAILED',reasonCode:'APPLICATION_REQUEST_FAILED',reason:'Application request failed or timed out.'};}}
async function startScan(){if(scan.disabled)return;const a=input.value.trim();if(!/^0x[0-9a-f]{40}$/i.test(a)){$('helper').textContent='Enter a valid contract address.';return;}scan.disabled=true;$('token').classList.add('show');$('address').textContent=a;$('tokenName').textContent='Token scan';$('tokenMeta').textContent='';$('scanStatus').textContent='SCANNING';for(const name of Object.keys(cards))render(name,undefined);const supply={},views={};
const jobs=['token','supply','market','unlock','holders','control','liquidity','activity','mechanics'].map(async route=>{const d=await request(route,a);if(route==='token'){if(d.ok&&d.token){$('tokenName').textContent=(d.token.name||'Token')+(d.token.symbol?' ('+d.token.symbol+')':'');$('tokenMeta').textContent='Arc · Chain 5042 · Decimals: '+d.token.decimals;}else $('tokenMeta').textContent='Token metadata unavailable.';return;}
if(['supply','market','unlock'].includes(route)){supply[route]=d;views.supply=render('supply',supply);}else{const name=route==='holders'?'whales':route;views[name]=render(name,d);}});
await Promise.allSettled(jobs);const fields=Object.values(views).flatMap(x=>x.fields),found=fields.filter(x=>x.dataState==='DATA_FOUND').length,mappingFailed=fields.some(x=>x.dataState==='FRONTEND_MAPPING_FAILED');$('scanStatus').textContent=mappingFailed?'DATA MAPPING FAILED':found?'PARTIAL EVIDENCE':'NO VERIFIED RESULTS';$('helper').textContent=found+' of 24 summary fields have evidence. Open View Evidence for source failures, missing data and verification limits.';scan.disabled=false;}
scan.addEventListener('click',startScan);input.addEventListener('keydown',e=>{if(e.key==='Enter')startScan();});
