const c=require('./core'),source=require('./verified-source');
const slots={implementation:'0x360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc',admin:'0xb53127684a568b3173ae13b9f8a6016e243e63b6e8ee1178d6a717850b5d6103',beacon:'0xa3f0ad74e5423aebfd80d3ef4346578335a9a72aeaee59ff6cb3582b35133d50'};
function pushes(code){const b=Buffer.from(code.slice(2),'hex'),out=[];for(let i=0;i<b.length;i++){const op=b[i];if(op>=0x60&&op<=0x7f){const n=op-0x5f;if(op===0x63&&i+4<b.length)out.push(b.subarray(i+1,i+5).toString('hex'));i+=n;}}return out;}
async function inspect(a){const {block,code}=await c.context(a),evidence=[];const readings=await Promise.allSettled(Object.entries(slots).map(async([name,slot])=>({name,address:c.addressWord(await c.rpc('eth_getStorageAt',[a,slot,block])),slot})));let implementation=null,admin=null,beacon=null;for(const r of readings)if(r.status==='fulfilled'){evidence.push({...r.value,block});if(r.value.address!==c.BURNS[0]){if(r.value.name==='implementation')implementation=r.value.address;if(r.value.name==='admin')admin=r.value.address;if(r.value.name==='beacon')beacon=r.value.address;}}else evidence.push({dataState:'SOURCE_API_FAILED',...c.failure(r.reason)});
if(!implementation&&beacon){try{implementation=c.addressWord(await c.call(beacon,'0x5c60da1b',block));evidence.push({method:'beacon.implementation()',address:beacon,implementation,block});}catch(e){evidence.push(c.failure(e));}}
const clone=code.match(/^0x363d3d373d3d3d363d73([0-9a-f]{40})5af43d82803e903d91602b57fd5bf3$/i);if(clone){implementation='0x'+clone[1].toLowerCase();evidence.push({method:'EIP-1167 runtime',implementation,address:a,block});}let implementationCode=null;if(implementation){try{const x=await c.rpc('eth_getCode',[implementation,block]);if(/^0x(?:[0-9a-f]{2})+$/i.test(x))implementationCode=x;}catch(e){evidence.push(c.failure(e));}}
let verified=await source.lookup(implementationCode?implementation:a,implementationCode||code),proxySource=null;
if(!implementation&&(verified.profile?.id==='FIAT_TOKEN_PROXY'||require('./generic-contract').isLegacy(code))){proxySource=source.summary(verified);const legacy={admin:'0x10d6a54a4754c8869d6886b5f5d7fbfa5b4522237ea5c60d11bc4e7a1ff9390b',implementation:'0x7050c9e0f4ca769c69bd3a8ef740bc37934f8e2c036e5a723fd8ee048ed3f8c3'};for(const [name,slot]of Object.entries(legacy)){try{const address=c.addressWord(await c.rpc('eth_getStorageAt',[a,slot,block]));evidence.push({name,address,slot,block,source:'Legacy ZeppelinOS implementation slot and delegatecall/source evidence'});if(address!==c.BURNS[0]){if(name==='admin')admin=address;else implementation=address;}}catch(err){evidence.push(c.failure(err));}}if(implementation){try{const target=await c.rpc('eth_getCode',[implementation,block]);if(/^0x(?:[0-9a-f]{2})+$/i.test(target)){implementationCode=target;verified=await source.lookup(implementation,target);}}catch(err){evidence.push(c.failure(err));}}}
const selectors=new Set([...pushes(code),...pushes(implementationCode||'0x')]);const abiNames=new Set(verified.abi?.filter(x=>x.type==='function').map(x=>x.name));
const candidates=[['mint','40c10f19'],['pause','8456cb59'],['unpause','3f4ba83a'],['AccessControl.hasRole','91d14854'],['burn','42966c68']].filter(([,s])=>selectors.has(s)).map(([name,selector])=>({name,selector:'0x'+selector,status:'CANDIDATE',address:implementationCode?implementation:a}));
let owner=c.unknown('No validated owner getter response.','OWNER_GETTER_NOT_VALIDATED'),paused=c.unknown('No validated paused getter response.','PAUSED_GETTER_NOT_VALIDATED'),accessControl=c.unknown('No validated role implementation.','ACCESS_CONTROL_NOT_ESTABLISHED');
const probes=await Promise.allSettled(['0x8da5cb5b','0x5c975abb','0x01ffc9a77965db0b'+'0'.repeat(56)].map(s=>c.call(a,s,block)));
if(probes[0].status==='fulfilled'&&(selectors.has('8da5cb5b')||abiNames.has('owner'))){try{owner=c.fact(c.addressWord(probes[0].value),[{method:'owner()',address:a,block}],'GETTER_REPORTED');}catch{owner=c.unknown('Owner return data is not an ABI address.','MALFORMED_OWNER_GETTER');}}else if(probes[0].status==='rejected'){const f=c.failure(probes[0].reason);owner=c.unknown('owner() did not return validated data.','OWNER_GETTER_CALL_FAILED',f.dataState);owner.failure=f;}
if(probes[1].status==='fulfilled'&&(selectors.has('5c975abb')||abiNames.has('paused'))){try{const x=c.uint(probes[1].value);if(x<=1n)paused=c.fact(x===1n,[{method:'paused()',address:a,block}],'GETTER_REPORTED');}catch{}}
if(probes[2].status==='fulfilled'&&(selectors.has('01ffc9a7')||abiNames.has('supportsInterface'))){try{if(c.uint(probes[2].value)===1n)accessControl=c.fact(true,[{method:'supportsInterface(0x7965db0b)',address:a,block}],'INTERFACE_REPORTED');}catch{}}
let initialized=null;
if(verified.profile&&(clone||!implementation)){const entry=verified.storageLayout?.storage?.find(x=>x.label==='_initialized');if(entry){try{const h=await c.rpc('eth_getStorageAt',[a,'0x'+BigInt(entry.slot).toString(16),block]);const v=(c.uint(h)>>BigInt(Number(entry.offset)*8))&255n;if(v<=1n)initialized=v===1n;evidence.push({method:'reviewed initialized storage',slot:entry.slot,offset:entry.offset,value:initialized,block});}catch(e){evidence.push(c.failure(e));}}}
let mint=c.unknown('No reviewed mint path for this runtime.','MINT_PATH_NOT_REVIEWED'),pause=c.unknown('Paused state does not prove pause authority.','PAUSE_CONTROL_NOT_REVIEWED'),blacklist=c.unknown('No reviewed blacklist path for this runtime.','BLACKLIST_PATH_NOT_REVIEWED');
if(verified.profile?.id.startsWith('ARGUS')&&(clone||!implementation)){const proof=[{source:'Sourcify',sourceDigest:verified.sourceDigest,implementation:implementation||a,profile:verified.profile.id,block,scope:'Reviewed token implementation; external DEX contracts are separate'}];pause=c.fact(false,proof,'NOT_DETECTED');blacklist=c.fact(false,proof,'NOT_DETECTED');accessControl=c.fact(false,proof,'NOT_DETECTED');if(initialized===true)mint=c.fact(false,proof.concat({method:'initialization guard already set'}),'NOT_DETECTED');else mint=c.unknown('Initialization-only mint exists; initialization state is not confirmed.','INITIALIZATION_STATE_NOT_VERIFIED');}
const roles={};let ownerAuthority=c.unknown('Owner permission scope has not been reviewed.','OWNER_PERMISSION_SCOPE_NOT_REVIEWED');
if(verified.profile?.id==='ARGUS_V4_LAUNCH_TOKEN_7')ownerAuthority=c.fact('OBSERVATIONAL_OWNER_ONLY',[{sourceDigest:verified.sourceDigest,scope:'Owner is recorded at initialization; no privileged owner setter exists in the reviewed token runtime.'}],'VERIFIED_SOURCE');
if(verified.profile?.id==='ARGUS_TAX_TOKEN')ownerAuthority=c.fact('REDUCE_TAXES_DOWN_ONLY_AND_RENOUNCE',[{sourceDigest:verified.sourceDigest}],'VERIFIED_SOURCE');
if(verified.profile?.id==='FIAT_TOKEN_V2_2'){const proof=[{source:'Sourcify',sourceDigest:verified.sourceDigest,implementation:implementation||a,block,scope:'Current token implementation; proxy admin may upgrade it.'}];const names=[['masterMinter','0x35d99f35'],['pauser','0x9fd0506d'],['blacklister','0xbd102430']];for(const [name,selector]of names){try{roles[name]=c.fact(c.addressWord(await c.call(a,selector,block)),proof.concat({method:name+'()',address:a,block}),'GETTER_REPORTED');}catch(err){roles[name]=c.unknown(name+' getter did not return a validated address.','ROLE_GETTER_FAILED',c.failure(err).dataState);}}
mint=c.fact(true,proof.concat({method:'mint: onlyMinters; configureMinter: onlyMasterMinter; allowance and paused/blacklist guards'}),'DETECTED');pause=c.fact(true,proof.concat({method:'pause/unpause: onlyPauser; owner updates pauser'}),'DETECTED');blacklist=c.fact(true,proof.concat({method:'blacklist/unBlacklist: onlyBlacklister; owner updates blacklister'}),'DETECTED');accessControl=c.fact('CUSTOM_ROLE_GATES',proof,'DETECTED');ownerAuthority=c.fact('OWNER_UPDATES_PAUSER_BLACKLISTER_MASTER_MINTER',proof,'VERIFIED_SOURCE');}
const generic=await require('./generic-contract').inspect(a,verified,block);if(owner.value===null){const alternate=generic.ownership.getOwner||generic.ownership.owner;if(alternate?.value)owner=alternate;}let genericAdmin=null;if(!admin){const alternate=[generic.ownership.admin,generic.ownership.getAdmin,generic.roleState.enumerableAdmin].find(x=>x?.value&&!c.BURNS.includes(x.value));if(alternate){admin=alternate.value;genericAdmin=alternate;}}let securitySource=null;if([mint,pause,blacklist,owner].some(x=>x.value===null)){try{securitySource=await require('./goplus').read(a);if(mint.value===null){const v=require('./goplus').flag(securitySource,'is_mintable');if(v.value!==null)mint=v;}if(pause.value===null){const v=require('./goplus').flag(securitySource,'transfer_pausable');if(v.value!==null)pause=v;}if(blacklist.value===null){const v=require('./goplus').flag(securitySource,'is_blacklisted');if(v.value!==null)blacklist=v;}const address=securitySource.data?.owner_address;if(owner.value===null&&securitySource.data?.is_open_source==='1'&&/^0x[0-9a-f]{40}$/i.test(address||''))owner={...require('./fields').field(address.toLowerCase(),'MARKET_API_VERIFIED','GoPlus',require('./goplus').proof(securitySource,'owner_address'),'MEDIUM'),scope:'Source-reported owner; permission scope not independently established.'};}catch(e){securitySource={...c.failure(e)};}}return {securitySource,generic,block,source:'Arc RPC / Sourcify',status:'PARTIAL_EVIDENCE',dataState:'DATA_FOUND',mint,pause,blacklist,owner,admin:admin?(genericAdmin||c.fact(admin,evidence.filter(x=>x.name==='admin'))):c.unknown('Standard EIP-1967 admin slot is zero or unreadable; this does not prove no other admin.','NO_STANDARD_ADMIN_EVIDENCE'),paused,accessControl,proxy:implementation&&implementationCode?c.fact(implementation,evidence,'DETECTED'):c.unknown('No validated standard implementation; custom proxy forms remain possible.','NO_STANDARD_PROXY_EVIDENCE'),implementation,implementationInspected:!!implementationCode,beacon,candidates,evidence,verifiedSource:source.summary(verified),proxySource,roles,ownerAuthority,initialized,scope:'Token-level capability evidence. Hook/DEX authority is not inferred.'};}
module.exports={inspect:a=>require('./fields').cached('control:'+a,10000,()=>inspect(a)),slots,pushes};
