// Durable holder documents are independent of the short-lived fields/API cache.
const fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os'),crypto=require('node:crypto'),{AsyncLocalStorage}=require('node:async_hooks'),c=require('./core'),health=require('./search-health'),budget=require('./holder-budget');
const scope=new AsyncLocalStorage(),localLeases=new Map(),CHAIN=5042,LEASE_MS=120000;
const addressPattern=/^0x[0-9a-f]{40}$/,word=/^0x[0-9a-f]{64}$/,block=/^0x[0-9a-f]+$/;
const dir=()=>process.env.ARC_INDEX_CACHE_DIR||path.join(os.tmpdir(),'arcy-holder-index-v1');
function identity(name){if(!/^0x[0-9a-f]{40}(?:-candidates)?$/.test(name))throw Object.assign(Error(),{code:'INVALID_HOLDER_STORAGE_KEY'});return name.slice(0,42);}
function mode(){if(process.env.ARC_HOLDER_STORAGE==='local')return 'local';const {url,token}=require('./redis-config')();if(Boolean(url)!==Boolean(token))throw Object.assign(Error(),{code:'STORAGE_CONFIGURATION_INCOMPLETE'});return url?'redis':'local';}
const key=name=>'holders:v2:'+CHAIN+':'+name,lockKey=name=>key(name)+':lease';
function storageError(){health.record('STORAGE_UNAVAILABLE');return Object.assign(Error('Holder storage unavailable'),{code:'STORAGE_UNAVAILABLE'});}
async function command(args){try{const {url,token}=require('./redis-config')();const d=await budget.operation(()=>c.json(url,{method:'POST',headers:{authorization:'Bearer '+token,'content-type':'application/json'},body:JSON.stringify(args)}));if(!d||d.error||!Object.hasOwn(d,'result'))throw Error();return d.result;}catch(e){if(e.code==='HOLDER_WORKER_BUDGET_EXHAUSTED')throw e;if(e.httpStatus===429)health.record('STORAGE_RATE_LIMITED',{httpStatus:429});throw storageError();}}
function validCheckpoint(s,a){
 if(!s||s.version!==1||s.chainId!==CHAIN||s.address!==a)return false;
 if(s.phase){if(!['DISCOVER','TAIL','CATCHUP','READ','COMPLETE'].includes(s.phase)||!Array.isArray(s.addresses)||s.addresses.length>100000||new Set(s.addresses).size!==s.addresses.length||s.addresses.some(x=>!addressPattern.test(x))||!Array.isArray(s.balances)||!Number.isSafeInteger(s.balanceCursor)||s.balanceCursor<0||s.balanceCursor!==s.balances.length||s.balanceCursor>s.addresses.length)return false;
  if(s.balances.some((entry,i)=>!Array.isArray(entry)||entry.length!==2||entry[0]!==s.addresses[i]||!/^\d+$/.test(entry[1])))return false;
  if(!Number.isFinite(s.startedAt)||s.startedAt>Date.now()||((s.phase==='DISCOVER'||s.phase==='TAIL'||s.phase==='CATCHUP')&&s.balanceCursor!==0)||(s.balanceCursor>0&&!s.block)||(s.tailRange!==undefined&&(!Number.isSafeInteger(s.tailRange)||s.tailRange<1||s.tailRange>1000)))return false;
  if(s.phase==='DISCOVER'&&(!Number.isSafeInteger(s.offset)||s.offset<0))return false;
  if(s.block&&(!block.test(s.block)||!word.test(s.anchor||'')||!/^\d+$/.test(s.total||'')))return false;
  if(s.phase==='CATCHUP'&&(!s.block||!Number.isSafeInteger(s.catchupCursor)||!Number.isSafeInteger(s.catchupStart)||s.catchupStart<0||s.catchupCursor<s.catchupStart||s.catchupCursor>Number(BigInt(s.block))+1||(s.catchupRange!==undefined&&(!Number.isSafeInteger(s.catchupRange)||s.catchupRange<1||s.catchupRange>1000))))return false;
  if(s.phase==='TAIL'&&(!block.test(s.previousBlock||'')||!word.test(s.previousAnchor||'')||!Number.isSafeInteger(s.tailCursor)||s.tailCursor<Number(BigInt(s.previousBlock))+1))return false;
  if(s.phase==='COMPLETE'&&(!validSnapshot(s.result,a)||s.result.block!==s.block||s.balanceCursor!==s.addresses.length||s.completedAt!==Date.parse(s.result.snapshot.completedAt)||!/^\d+$/.test(s.total||'')))return false;
  return true;
 }
 return Number.isSafeInteger(s.cursor)&&s.cursor>=-1&&Number.isSafeInteger(s.range)&&s.range>=1&&s.balances&&typeof s.balances==='object'&&!Array.isArray(s.balances)&&Object.entries(s.balances).every(([a,v])=>addressPattern.test(a)&&/^\d+$/.test(v))&&(s.cursor===-1||word.test(s.cursorHash||''));
}
function validSnapshot(s,a){return s?.coverage?.complete===true&&s.status==='ONCHAIN_VERIFIED'&&block.test(s.block||'')&&s.snapshot?.block===s.block&&Array.isArray(s.evidence)&&s.evidence.some(e=>e.block===s.block&&word.test(e.anchor||''))&&Number.isSafeInteger(s.holderCount)&&s.holderCount>=0&&['largestWalletPct','top10Pct','top20Pct'].every(k=>Number.isFinite(s[k])&&s[k]>=0&&s[k]<=100)&&s.largestWalletPct<=s.top10Pct&&s.top10Pct<=s.top20Pct&&['holderCount','largestWalletPct','top10Pct','top20Pct'].every(k=>s.fields?.[k]?.value===s[k]&&s.fields[k].dataState==='DATA_FOUND'&&s.fields[k].status==='ONCHAIN_VERIFIED'&&s.fields[k].evidence?.some(e=>e.block===s.block&&word.test(e.anchor||'')))&&Number.isFinite(Date.parse(s.snapshot?.completedAt||''))&&Date.parse(s.snapshot.completedAt)<=Date.now()&&(!s.address||s.address===a);}
async function raw(name){identity(name);try{let value;if(mode()==='redis'){value=await command(['GET',key(name)]);if(value===null){const legacy=await command(['GET','holders:v1:'+CHAIN+':'+name]);if(legacy!==null){try{return {schemaVersion:2,chainId:CHAIN,contract:identity(name),revision:0,checkpoint:JSON.parse(legacy),completedSnapshot:null,migratedFrom:1};}catch{health.record('CHECKPOINT_CORRUPT');return null;}}}}else{try{value=await fs.readFile(path.join(dir(),name+'.v2.json'),'utf8');}catch(e){if(e.code!=='ENOENT')throw e;try{const legacy=JSON.parse(await fs.readFile(path.join(dir(),name+'.json'),'utf8'));return {schemaVersion:2,chainId:CHAIN,contract:identity(name),revision:0,checkpoint:legacy,completedSnapshot:null,migratedFrom:1};}catch(x){if(x.code!=='ENOENT'&&!(x instanceof SyntaxError))throw x;return null;}}}if(value===null)return null;try{const d=JSON.parse(value);if(d.schemaVersion!==2||d.chainId!==CHAIN||d.contract!==identity(name)||!Number.isSafeInteger(d.revision)||d.revision<0)throw Error();return d;}catch{health.record('CHECKPOINT_CORRUPT',{contract:identity(name)});return null;}}catch(e){if(['HOLDER_WORKER_BUDGET_EXHAUSTED','STORAGE_UNAVAILABLE','STORAGE_CONFIGURATION_INCOMPLETE'].includes(e.code))throw e;throw storageError();}}
function verifiedCompleted(d,name){const s=d?.completedSnapshot||d?.checkpoint?.result;if(!validSnapshot(s,identity(name)))return null;const full=d.completedIndex||((d.checkpoint?.phase==='COMPLETE')?{block:d.checkpoint.block,totalSupplyRaw:d.checkpoint.total,balances:d.checkpoint.balances,candidateAddresses:d.checkpoint.addresses}:null);if(!full||full.block!==s.block||!Array.isArray(full.balances)||!Array.isArray(full.candidateAddresses)||full.balances.length!==full.candidateAddresses.length||full.balances.some((e,i)=>!Array.isArray(e)||e[0]!==full.candidateAddresses[i]||!addressPattern.test(e[0])||!/^\d+$/.test(e[1])))return null;try{const metrics=require('./holder-index').aggregate(full.balances,BigInt(full.totalSupplyRaw),s.evidence);if(['holderCount','largestWalletPct','top10Pct','top20Pct'].some(k=>metrics[k]!==s[k]))return null;}catch{return null;}return s;}
async function load(name){const d=await raw(name);if(!d)return null;if(!validCheckpoint(d.checkpoint,identity(name))){health.record('CHECKPOINT_CORRUPT',{contract:identity(name)});const previous=verifiedCompleted(d,name),full=d.completedIndex;if(previous&&full){return {version:1,address:identity(name),chainId:CHAIN,phase:'COMPLETE',startedAt:Date.parse(previous.snapshot.completedAt),completedAt:Date.parse(previous.snapshot.completedAt),block:previous.block,anchor:previous.evidence.find(e=>e.block===previous.block).anchor,total:full.totalSupplyRaw,addresses:full.candidateAddresses,balances:full.balances,balanceCursor:full.balances.length,result:previous};}return null;}return d.checkpoint;}
async function snapshot(name){const d=await raw(name),s=verifiedCompleted(d,name);if(!s)return null;if(d.migratedFrom===1&&validCheckpoint(d.checkpoint,identity(name)))await withLease(name,()=>save(name,d.checkpoint));return s;}
async function invalidate(name,pinnedBlock){return withLease(name,async()=>save(name,{version:1,address:identity(name),chainId:CHAIN,startedAt:Date.now(),phase:'DISCOVER',offset:0,addresses:[],balances:[],balanceCursor:0,invalidatedSnapshotBlock:pinnedBlock}));}
const commitScript="if redis.call('GET',KEYS[1]) ~= ARGV[1] then return 0 end redis.call('SET',KEYS[2],ARGV[2]) redis.call('PEXPIRE',KEYS[1],ARGV[3]) return 1";
const releaseScript="if redis.call('GET',KEYS[1]) == ARGV[1] then return redis.call('DEL',KEYS[1]) end return 0";
async function acquire(name){identity(name);const token=crypto.randomUUID();if(mode()==='redis'){if(await command(['SET',lockKey(name),token,'NX','PX',LEASE_MS])!=='OK')return null;}else{if(localLeases.has(name))return null;localLeases.set(name,token);}return {name,token,mode:mode()};}
async function release(lease){if(lease.mode==='redis')await command(['EVAL',releaseScript,1,lockKey(lease.name),lease.token]);else if(localLeases.get(lease.name)===lease.token)localLeases.delete(lease.name);}
async function withLease(name,fn){const lease=await acquire(name);if(!lease){health.record('HOLDER_JOB_COALESCED',{contract:identity(name)});return {busy:true};}try{return await scope.run(lease,fn);}finally{try{await budget.cleanup(()=>release(lease));}catch(e){health.record(e.code==='HOLDER_WORKER_BUDGET_EXHAUSTED'?'HOLDER_WORKER_YIELDED':'STORAGE_UNAVAILABLE');}}}
async function save(name,s){budget.check();identity(name);if(!validCheckpoint(s,identity(name)))throw Object.assign(Error('Invalid holder checkpoint'),{code:'CORRUPTED_HOLDER_CHECKPOINT'});const lease=scope.getStore();if(!lease||lease.name!==name){return withLease(name,async()=>save(name,s)).then(r=>{if(r?.busy)throw Object.assign(Error(),{code:'HOLDER_JOB_BUSY'});});}
 const previous=await raw(name);let completed=s.phase==='COMPLETE'?structuredClone(s.result):previous?.completedSnapshot||previous?.checkpoint?.result||null;
 if(s.invalidatedSnapshotBlock===completed?.block)completed=null;
 let completedIndex=previous?.completedIndex||null;
 if(s.phase==='COMPLETE'){if(previous?.completedSnapshot&&BigInt(s.block)<BigInt(previous.completedSnapshot.block))throw Object.assign(Error(),{code:'HOLDER_SNAPSHOT_BLOCK_REGRESSED'});const verified=require('./holder-index').aggregate(s.balances,BigInt(s.total),s.result.evidence);for(const k of ['holderCount','largestWalletPct','top10Pct','top20Pct'])if(verified[k]!==s.result[k])throw Object.assign(Error(),{code:'CORRUPTED_HOLDER_SNAPSHOT'});completedIndex={block:s.block,totalSupplyRaw:s.total,candidateAddresses:s.addresses,balances:s.balances,activeHolderAddresses:s.balances.filter(([a,v])=>BigInt(v)>0n&&!c.BURNS.includes(a)).map(([a])=>a)};}
 if(!completed)completedIndex=null;
 const d={schemaVersion:2,checkpointVersion:1,chainId:CHAIN,contract:identity(name),revision:(previous?.revision||0)+1,stage:s.phase==='COMPLETE'?'COMPLETE':s.phase==='READ'?'RECONCILING':'BUILDING',updatedAt:new Date().toISOString(),lastFullyIndexedBlock:s.phase?(s.phase==='COMPLETE'?Number(BigInt(s.block)):s.transferTail?.toBlock??(s.phase==='TAIL'?s.tailCursor-1:previous?.lastFullyIndexedBlock??null)):s.cursor,lastSuccessfulReconciliationBlock:validSnapshot(completed,identity(name))?completed.block:null,checkpoint:s,completedSnapshot:validSnapshot(completed,identity(name))?completed:null,completedIndex};
 const body=JSON.stringify(d);if(lease.mode==='redis'){if(await command(['EVAL',commitScript,2,lockKey(name),key(name),lease.token,body,LEASE_MS])!==1)throw Object.assign(Error(),{code:'HOLDER_LEASE_LOST'});}else{if(localLeases.get(name)!==lease.token)throw Object.assign(Error(),{code:'HOLDER_LEASE_LOST'});try{await fs.mkdir(dir(),{recursive:true});const file=path.join(dir(),name+'.v2.json'),tmp=file+'.'+crypto.randomUUID()+'.tmp';await fs.writeFile(tmp,body);await fs.rename(tmp,file);}catch{throw storageError();}}
 if(s.phase==='COMPLETE')health.record('HOLDER_REFRESH_SUCCESS',{contract:identity(name),block:s.block});
}
const queueKey='holders:v2:'+CHAIN+':refresh-queue';let localQueueTask=Promise.resolve();
async function localQueue(fn){const task=localQueueTask.catch(()=>{}).then(async()=>{await fs.mkdir(dir(),{recursive:true});const file=path.join(dir(),'refresh-queue.v2.json');let jobs={};try{jobs=JSON.parse(await fs.readFile(file,'utf8'));}catch(e){if(e.code!=='ENOENT')throw storageError();}const result=fn(jobs);const tmp=file+'.'+crypto.randomUUID()+'.tmp';await fs.writeFile(tmp,JSON.stringify(jobs));await fs.rename(tmp,file);return result;});localQueueTask=task;return task;}
async function enqueue(a,at=Date.now(),replace=false){identity(a);const name=a+'-candidates';if(mode()==='redis'){const script="if redis.call('ZSCORE',KEYS[1],ARGV[1]) == false and redis.call('ZCARD',KEYS[1]) >= 1000 then return 0 end if ARGV[3] == '1' then redis.call('ZADD',KEYS[1],ARGV[2],ARGV[1]) else redis.call('ZADD',KEYS[1],'NX',ARGV[2],ARGV[1]) end return 1";return await command(['EVAL',script,1,queueKey,name,Math.floor(at),replace?'1':'0'])===1;}return localQueue(jobs=>{if(!Object.hasOwn(jobs,name)&&Object.keys(jobs).length>=1000)return false;if(replace||!Object.hasOwn(jobs,name))jobs[name]=Math.floor(at);return true;});}
async function due(limit=1){limit=Math.max(1,Math.min(5,limit));let names;if(mode()==='redis')names=await command(['ZRANGEBYSCORE',queueKey,'-inf',Date.now(),'LIMIT',0,limit]);else names=await localQueue(jobs=>Object.entries(jobs).filter(([,at])=>at<=Date.now()).sort((a,b)=>a[1]-b[1]).slice(0,limit).map(([name])=>name));if(!Array.isArray(names)||names.some(n=>!/^0x[0-9a-f]{40}-candidates$/.test(n)))throw storageError();return names.map(n=>identity(n));}
module.exports={load,save,snapshot,withLease,invalidate,validCheckpoint,validSnapshot,mode,identity,enqueue,due};
