const SOURCES=[
 {url:'https://www.arc.io/blog',family:'Official Arc blog',owner:'OFFICIAL ARC',type:'arc-blog',priority:5,arcNative:true},
 {url:'https://community.arc.io/public/blogs',family:'Official Arc community',owner:'OFFICIAL ARC COMMUNITY',type:'links',priority:4,arcNative:true},
 {url:'https://www.circle.com/pressroom',family:'Official Circle pressroom',owner:'OFFICIAL CIRCLE',type:'links',priority:3},
 {url:'https://www.circle.com/blog',family:'Official Circle blog',owner:'OFFICIAL CIRCLE',type:'links',priority:3},
 {url:'https://arction.app/docs/roadmap',family:'Active Arc project roadmap',owner:'OFFICIAL ARCTION',type:'catalog',priority:2,arcNative:true}
];
const WEEK=7*86400000,REFRESH_HOUR_UTC=6,EDITION_START=Date.UTC(2026,8,28);
function strip(value=''){return String(value).replace(/<[^>]*>/g,' ').replace(/&amp;/g,'&').replace(/&#39;/g,"'").replace(/&quot;/g,'"').replace(/\s+/g,' ').trim();}
function absolute(href,base){try{return new URL(href,base).href;}catch{return '';}}
function cycle(now=Date.now()){const value=new Date(now),mondayOffset=(value.getUTCDay()+6)%7,start=Date.UTC(value.getUTCFullYear(),value.getUTCMonth(),value.getUTCDate()-mondayOffset);return {start,end:start+WEEK};}
function number(now=Date.now()){return Math.max(1,Math.floor((cycle(now).start-EDITION_START)/WEEK)+1);}
function isoWeek(now=Date.now()){const value=new Date(cycle(now).start),year=value.getUTCFullYear(),firstThursday=new Date(Date.UTC(year,0,4)),offset=(firstThursday.getUTCDay()+6)%7,firstMonday=Date.UTC(year,0,4-offset);if(value.getTime()<firstMonday)return isoWeek(Date.UTC(year-1,11,31));return {year,week:Math.floor((value.getTime()-firstMonday)/WEEK)+1};}
function cacheKey(now=Date.now()){const value=isoWeek(now);return `pulse:${value.year}-W${String(value.week).padStart(2,'0')}`;}
function nextRun(now=Date.now()){return new Date(cycle(now).end+REFRESH_HOUR_UTC*3600000).toISOString();}
function dateFromText(title,url){const text=[title,new URL(url).pathname].join(' '),matches=[...text.matchAll(/(?:20\d{2}-\d{2}-\d{2}|(?:January|February|March|April|May|June|July|August|September|October|November|December|Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\.?\s+\d{1,2}(?:st|nd|rd|th)?,?\s+20\d{2})/gi)];if(!matches.length)return null;const raw=matches[0][0].replace(/(\d)(?:st|nd|rd|th)\b/i,'$1');if(/^20\d{2}-\d{2}-\d{2}$/.test(raw))return new Date(`${raw}T00:00:00.000Z`).toISOString();const parts=raw.match(/^(January|February|March|April|May|June|July|August|September|October|November|December|Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\.?\s+(\d{1,2}),?\s+(20\d{2})$/i);if(!parts)return null;const month={jan:0,feb:1,mar:2,apr:3,may:4,jun:5,jul:6,aug:7,sep:8,oct:9,nov:10,dec:11}[parts[1].slice(0,3).toLowerCase()],date=new Date(Date.UTC(Number(parts[3]),month,Number(parts[2])));return date.getUTCFullYear()===Number(parts[3])&&date.getUTCMonth()===month?date.toISOString():null;}
function articleMeta(html,fallback){let structured=false;for(const match of String(html).matchAll(/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)){structured=true;try{const parsed=JSON.parse(strip(match[1])),nodes=Array.isArray(parsed)?parsed:(parsed['@graph']||[parsed]);for(const node of nodes){const types=Array.isArray(node['@type'])?node['@type']:[node['@type']];if(types.includes('BlogPosting')&&node.headline&&node.datePublished){const publishedAt=new Date(node.datePublished);if(!Number.isFinite(publishedAt.getTime()))throw Object.assign(Error('SOURCE_PARSE_FAILURE'),{code:'SOURCE_PARSE_FAILURE'});return {title:String(node.headline),url:node.mainEntityOfPage||node.url||fallback,publishedAt:publishedAt.toISOString()};}}}catch(error){if(error?.code==='SOURCE_PARSE_FAILURE')throw error;throw Object.assign(Error('SOURCE_PARSE_FAILURE'),{code:'SOURCE_PARSE_FAILURE'});}}if(structured)throw Object.assign(Error('SOURCE_PARSE_FAILURE'),{code:'SOURCE_PARSE_FAILURE'});return null;}
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function request(fetcher,url){let failure;for(let attempt=0;attempt<2;attempt++){try{const response=await fetcher(url,{headers:{'user-agent':'ARCY-Pulse/1.0'},signal:AbortSignal.timeout(15000)});if(response.ok||(![408,429].includes(response.status)&&response.status<500))return response;failure=Object.assign(Error(`HTTP_${response.status}`),{code:`HTTP_${response.status}`});}catch(error){failure=error;}if(attempt===0)await delay(150);}throw failure||Object.assign(Error('SOURCE_UNAVAILABLE'),{code:'SOURCE_UNAVAILABLE'});}
function relevant(title,source){return source.arcNative||/\barc(?:\s+(?:mainnet|network|ecosystem|chain|native|integration|developer|liquidity|payments?|stablecoin))?\b/i.test(title);}
async function collectLinks(source,fetcher){const response=await request(fetcher,source.url);if(!response.ok)throw Object.assign(Error(`HTTP_${response.status}`),{code:`HTTP_${response.status}`});const html=await response.text(),items=[],links=/<a[^>]+href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi;let match;while((match=links.exec(html))){const title=strip(match[2]),url=absolute(match[1],source.url);if(title.length<18||!url)continue;const target=new URL(url),origin=new URL(source.url);if(target.origin!==origin.origin||!target.pathname.startsWith(origin.pathname+'/'))continue;items.push({title,url,publishedAt:dateFromText(title,url),owner:source.owner,source:source.family,priority:source.priority,arcRelevant:relevant(title,source)});}return items;}
async function collectArcBlog(source,fetcher){const response=await request(fetcher,source.url);if(!response.ok)throw Object.assign(Error(`HTTP_${response.status}`),{code:`HTTP_${response.status}`});const html=await response.text(),links=[];for(const match of html.matchAll(/href=["']([^"']+)["']/gi)){const url=absolute(match[1],source.url);if(url&&new URL(url).origin===new URL(source.url).origin&&/^\/blog\/[^/]+/.test(new URL(url).pathname)&&!links.includes(url))links.push(url);}return Promise.all(links.slice(0,12).map(async url=>{const article=await request(fetcher,url);if(!article.ok)throw Object.assign(Error(`HTTP_${article.status}`),{code:`HTTP_${article.status}`});const meta=articleMeta(await article.text(),url);if(!meta)throw Object.assign(Error('SOURCE_PARSE_FAILURE'),{code:'SOURCE_PARSE_FAILURE'});return {...meta,url:absolute(meta.url,url),owner:source.owner,source:source.family,priority:source.priority,arcRelevant:true};}));}
async function check(source,fetcher){try{if(source.type==='catalog'){const response=await request(fetcher,source.url);if(!response.ok)throw Object.assign(Error(`HTTP_${response.status}`),{code:`HTTP_${response.status}`});return {items:[],audit:{family:source.family,url:source.url,status:'checked',candidates:0}};}const items=source.type==='arc-blog'?await collectArcBlog(source,fetcher):await collectLinks(source,fetcher);return {items,audit:{family:source.family,url:source.url,status:'checked',candidates:items.length}};}catch(error){const code=error?.code==='SOURCE_PARSE_FAILURE'?'SOURCE_PARSE_FAILURE':/^HTTP_\d+$/.test(error?.code||'')?error.code:'SOURCE_UNAVAILABLE';return {items:[],failed:true,audit:{family:source.family,url:source.url,status:'unavailable',candidates:0,errorCode:code}};}}
function score(item){return (item.priority||0)*10+(/\b(live|launch|mainnet|integration|deploy|payment|liquidity|stablecoin|privacy|fx|interop|developer|infrastructure)\b/i.test(item.title)?1:0);}
function select(items,current){const seen=new Set(),accepted=[],rejected={stale:0,future:0,duplicate:0,undated:0,irrelevant:0};for(const item of items){if(item.arcRelevant===false){rejected.irrelevant++;continue;}const time=Date.parse(item.publishedAt||'');if(!Number.isFinite(time)){rejected.undated++;continue;}if(time<current.start){rejected.stale++;continue;}if(time>=current.end){rejected.future++;continue;}const title=`title:${item.title.toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()}`,url=`url:${item.url}`;if(seen.has(title)||seen.has(url)){rejected.duplicate++;continue;}seen.add(title);seen.add(url);accepted.push(item);}return {cards:accepted.sort((a,b)=>score(b)-score(a)||Date.parse(b.publishedAt)-Date.parse(a.publishedAt)||a.title.localeCompare(b.title)).slice(0,3),rejected};}
function quietCards(now,start=0){const messages=[{owner:'ARC ECOSYSTEM',kind:'week',title:'No major verified update this week.',summary:'Configured first-party Arc sources were checked for this cycle. No stale announcement was reused.'},{owner:'SOURCE COVERAGE',kind:'new',title:'No additional verified development.',summary:'No qualifying current-cycle development was published by the checked source families.'},{owner:'NEXT REVIEW',kind:'watch',title:'Weekly source review continues.',summary:'Pulse will check the same first-party sources again in the next Monday UTC cycle.'}];return messages.slice(start).map(message=>({...message,publishedAt:new Date(now).toISOString(),url:''}));}
function take(cards,status){if(status==='quiet_week')return 'No major verified update this week. The configured first-party Arc sources were checked, and no stale announcement was reused. Track published schedules in Token Unlocks.';const headline=cards.find(card=>card.url)?.title||'the verified Arc developments';return `The signal this week is ${headline.replace(/[.?!]+$/,'')}. Watch for measurable usage, liquidity and settlement activity before treating announcements as adoption. Track published schedules in Token Unlocks.`;}
async function generate({now=Date.now(),fetcher=fetch,trigger='manual'}={}){const current=cycle(now),checks=await Promise.all(SOURCES.map(source=>check(source,fetcher))),available=checks.filter(check=>!check.failed),result=select(available.flatMap(check=>check.items),current),audit={cacheKey:cacheKey(now),cycle:{start:new Date(current.start).toISOString(),end:new Date(current.end).toISOString()},sourcesAttempted:checks.length,sourcesSuccessfullyChecked:available.length,sourceFailures:checks.filter(check=>check.failed).map(check=>check.audit),sourcesChecked:checks.map(check=>check.audit),candidateCount:available.reduce((sum,check)=>sum+check.items.length,0),acceptedItemCount:result.cards.length,rejected:result.rejected};if(!available.length){const error=Object.assign(Error('PULSE_DISCOVERY_UNAVAILABLE'),{code:'PULSE_DISCOVERY_UNAVAILABLE',audit});throw error;}const actual=result.cards.map((item,index)=>({owner:item.owner,publishedAt:item.publishedAt,kind:['week','new','watch'][index],title:item.title,summary:index===0?'The strongest verified Arc development from the current cycle. Open the primary source for scope.':index===1?'A verified current-cycle Arc development to track.':'A verified development worth watching for measurable follow-through.',url:item.url}));if(!actual.length&&audit.sourceFailures.length){const error=Object.assign(Error('PULSE_SOURCE_COVERAGE_INCOMPLETE'),{code:'PULSE_SOURCE_COVERAGE_INCOMPLETE',audit});throw error;}const status=actual.length?'updated':'quiet_week',cards=[...actual,...quietCards(now,actual.length)].slice(0,3);return {schemaVersion:1,number:number(now),generatedAt:new Date(now).toISOString(),trigger,success:true,status,cacheKey:audit.cacheKey,cycle:audit.cycle,cards,take:take(cards,status),sources:SOURCES.map(source=>source.url),audit};}
module.exports={SOURCES,cycle,number,isoWeek,cacheKey,nextRun,collectLinks,quietCards,generate};
