const c=require('../lib/core');
function aggregate(rows,a){if(!Array.isArray(rows))throw Error('Malformed pairs');const unique=new Map();for(const p of rows){if(p.chainId!=='arc'||![p.baseToken?.address,p.quoteToken?.address].some(x=>String(x).toLowerCase()===a)||!/^0x[0-9a-f]{40}(?:[0-9a-f]{24})?$/i.test(p.pairAddress||''))continue;const key=p.pairAddress.toLowerCase();if(!unique.has(key))unique.set(key,p);}const pairs=[...unique.values()].sort((a,b)=>(b.liquidity?.usd||0)-(a.liquidity?.usd||0));const sum=f=>pairs.length&&pairs.every(p=>typeof f(p)==='number'&&Number.isFinite(f(p))&&f(p)>=0)?pairs.reduce((n,p)=>n+f(p),0):null;return {dataState:pairs.length?'DATA_FOUND':'SOURCE_HAS_NO_DATA',reasonCode:pairs.length?null:'NO_MATCHING_ARC_PAIRS',reason:pairs.length?null:'DexScreener returned no exact contract-matched Arc pairs.',status:pairs.length?'SOURCE_REPORTED':'NOT_VERIFIED',liquidityUsd:sum(p=>p.liquidity?.usd),volume24h:sum(p=>p.volume?.h24),pairCount:pairs.length||null,dexCount:pairs.length&&pairs.every(p=>typeof p.dexId==='string'&&p.dexId.length)?new Set(pairs.map(p=>p.dexId)).size:null,primaryPair:pairs[0]?.pairAddress||null,pairs,lpStatus:c.unknown('Market liquidity does not prove LP locks or burns'),methodology:'Unique source-returned Arc pairs with exact base/quote contract match; counts and sums cover the returned dataset, not a guaranteed exhaustive chain-wide pool inventory. Market depth does not guarantee exit without slippage.'};}
module.exports=require('../lib/search-request').route(a=>require('../lib/fields').cached('liquidity:'+a,0,async()=>{
 const [tokenIdentity,pairRead]=await Promise.all([require('../lib/token-identity').inspect(a),require('../lib/market-activity').dexPairs(a).then(value=>({value}),error=>({error}))]);
 const attempts=[];let result;
 try{if(pairRead.error)throw pairRead.error;result=aggregate(pairRead.value,a);attempts.push({source:'DexScreener',dataState:result.dataState});}
 catch(e){result=aggregate([],a);attempts.push({source:'DexScreener',...c.failure(e)});}
 let source='DexScreener',pairEvidence=[{source,chainId:5042,address:a,scope:'Exact-contract source-returned pool dataset, not an exhaustive chain-wide inventory.'}];
 if(!result.pairs.length){try{const fallback=await require('../lib/gecko-pairs').read(a);attempts.push({source:'GeckoTerminal pools',dataState:fallback.pairs.length?'DATA_FOUND':'SOURCE_HAS_NO_DATA'});if(fallback.pairs.length){result=aggregate(fallback.pairs,a);source='GeckoTerminal';pairEvidence=fallback.evidence;result.methodology+=' Pool discovery fell back to the exact Arc contract first page on GeckoTerminal; counts cover only that returned dataset.';}}catch(e){attempts.push({source:'GeckoTerminal pools',...c.failure(e)});}}
 if(result.liquidityUsd===null){try{const g=await require('../lib/market-activity').gecko(a),reserve=require('../lib/market-activity').finite(g.attributes.total_reserve_in_usd,true);attempts.push({source:'GeckoTerminal token reserves',dataState:reserve!==null?'DATA_FOUND':'SOURCE_HAS_NO_DATA'});if(reserve!==null){result.liquidityUsd=reserve;result.liquiditySource='GeckoTerminal';result.liquidityEvidence=g.priceUsd.evidence;result.methodology+=' Liquidity USD uses contract-matched token reserves as a separate fallback dataset.';}}catch(e){attempts.push({source:'GeckoTerminal reserves',...c.failure(e)});}}
 result.marketAttempts=attempts;
 if(result.liquidityUsd!==null||result.volume24h!==null){result.dataState='DATA_FOUND';result.status='SOURCE_REPORTED';result.reasonCode=null;result.reason=null;}
 result.lpStatus=await require('../lib/lp-status').inspect(result.pairs,a);
 if(result.lpStatus.value===null){try{const security=await require('../lib/goplus').read(a),candidate=require('../lib/security-evidence').lp(security,result.pairs);result.lpEvidence=candidate;if(candidate.value!==null)result.lpStatus=candidate;}catch(e){result.lpFallbackFailure=c.failure(e);}}
 const field=(value,provider,evidence)=>({...require('../lib/fields').field(value,'MARKET_API_VERIFIED',provider,evidence),...(value===null?{dataState:attempts.some(x=>x.dataState==='SOURCE_API_FAILED')?'SOURCE_API_FAILED':'SOURCE_HAS_NO_DATA',reasonCode:attempts.some(x=>x.dataState==='SOURCE_API_FAILED')?'LIQUIDITY_FALLBACK_API_FAILED':'NO_CONTRACT_MATCHED_POOL_VALUE',attempts}: {})});
 result.fields={liquidityUsd:field(result.liquidityUsd,result.liquiditySource||source,result.liquidityEvidence||pairEvidence),volume24h:field(result.volume24h,source,pairEvidence),dexCount:field(result.dexCount,source,pairEvidence),pairCount:field(result.pairCount,source,pairEvidence),lpStatus:result.lpStatus};
 return {source,tokenIdentity,...result};
}));module.exports.aggregate=aggregate;
