const c=require('../lib/core');
function words(hex,count){if(!new RegExp('^0x[0-9a-fA-F]{'+count*64+'}$').test(hex))throw Error('Invalid tuple');return Array.from({length:count},(_,i)=>c.uint('0x'+hex.slice(2+i*64,2+(i+1)*64)));}
async function analyze(a){const control=await require('../lib/control').inspect(a);const unsupported='No bytecode-matched reviewed fee adapter for this runtime.';const result={status:'PARTIAL_EVIDENCE',dataState:'NOT_VERIFIED',source:'Arc RPC / Sourcify',block:control.block,buyTax:c.unknown(unsupported,'NO_REVIEWED_FEE_ADAPTER'),sellTax:c.unknown(unsupported,'NO_REVIEWED_FEE_ADAPTER'),transferTax:c.unknown(unsupported,'NO_REVIEWED_FEE_ADAPTER'),burnMechanism:c.unknown('Burn-address balances alone do not establish a burn flow.','BURN_FLOW_NOT_ESTABLISHED'),buybackAndBurn:c.unknown('No verified buyback processor or transaction flow.','BUYBACK_FLOW_NOT_ESTABLISHED'),burnAllocation:c.unknown('No verified allocation getter and units.','BURN_ALLOCATION_NOT_ESTABLISHED'),taxSettingsMutable:c.unknown('No reviewed fee setter and caller authority.','TAX_CHANGEABILITY_NOT_ESTABLISHED'),mint:control.mint,pause:control.pause,blacklist:control.blacklist,accessControl:control.accessControl,ownerAuthority:control.ownerAuthority,paused:control.paused,roles:control.roles,implementation:control.implementation,beacon:control.beacon,proxySource:control.proxySource,controlEvidence:control.evidence,owner:control.owner,admin:control.admin,proxy:control.proxy,verifiedSource:control.verifiedSource,candidates:control.candidates,implementationInspected:control.implementationInspected,generic:control.generic,buybackMechanism:control.generic?.buybackMechanismCandidates?.length?{...c.unknown('Verified interface contains buyback candidates; execution and burn linkage remain unverified.','BUYBACK_INTERFACE_ONLY'),evidence:control.generic.buybackMechanismCandidates}:c.unknown('No reviewed buyback mechanism.','BUYBACK_MECHANISM_NOT_VERIFIED'),buybackExecution:control.generic?.buybackExecution||c.unknown(),analysisCoverage:'UNRECOGNIZED_IMPLEMENTATION'};
const p=control.verifiedSource?.profile;if(!p||p.purpose==='PROXY')return fallback(result,a);
const proof=[{source:'Sourcify',sourceDigest:control.verifiedSource.sourceDigest,profile:p.id,implementation:control.implementation||a,block:control.block,scope:'Token transfer implementation. External swap/hook charges are distinct.'}];
result.transferTax={...c.fact(0,proof,'VERIFIED_SOURCE'),unit:'percent',scope:'Ordinary wallet-to-wallet ERC-20 transfers'};
result.burnMechanism={...c.fact(false,proof,'NOT_DETECTED'),scope:'No token-level supply-reducing burn entry point. Dead-address holdings do not reduce totalSupply.'};
result.dataState='DATA_FOUND';result.analysisCoverage='REVIEWED_TOKEN_PROFILE';
if(p.id==='ARGUS_V4_LAUNCH_TOKEN_7'){result.buyTax=c.unknown('Token has no transfer tax, but Uniswap V4 hook/swap charges are not verified. Zero token transfer tax must not be presented as a zero-cost buy.','V4_HOOK_FEE_NOT_VERIFIED');result.sellTax=c.unknown('Uniswap V4 hook/swap charges require separate verified pool-hook evidence.','V4_HOOK_FEE_NOT_VERIFIED');result.taxSettingsMutable={...c.fact(false,proof,'NOT_DETECTED'),scope:'Token has no fee settings or owner setters; external hook/config contracts are separate.'};return fallback(result,a);}
if(p.id==='FIAT_TOKEN_V2_2'){result.buyTax={...c.fact(0,proof,'VERIFIED_SOURCE'),unit:'percent',scope:'Token-level ERC-20 fee only. DEX/hook charges excluded; pause and blacklist may prevent a transfer.'};result.sellTax={...result.buyTax};result.burnMechanism={...c.fact(true,proof.concat({method:'burn(uint256): onlyMinters, whenNotPaused, notBlacklisted; reduces totalSupply.'}),'DETECTED'),scope:'Minter-controlled supply reduction; not evidence of buyback.'};result.taxSettingsMutable=control.proxySource?.profile?.id==='FIAT_TOKEN_PROXY'?c.fact('PROXY_UPGRADE_CONTROL',proof.concat(control.admin.evidence||[]),'VERIFIED_SOURCE_AND_STATE'):c.unknown('No token fee setter; future proxy changes require separate control proof.','PROXY_UPGRADE_CONTROL_NOT_ESTABLISHED');result.roles=control.roles;return result;}
if(p.id==='ARGUS_TAX_TOKEN'){const probes=await Promise.allSettled(['0xeb1e7387','0x79502c55','0xe7c2b772','0xa5a302d3','0xf3635019'].map(s=>c.call(a,s,control.block)));const e=method=>proof.concat({method,address:a,block:control.block});
try{if(probes[0].status!=='fulfilled'||probes[2].status!=='fulfilled')throw probes.find(x=>x.status==='rejected')?.reason||Error();const rates=words(probes[0].value,2),graduated=c.uint(probes[2].value);if(rates.some(x=>x>1000n)||graduated>1n)throw Error();const active=graduated===1n;result.buyTax={...c.fact(active?Number(rates[0])/100:0,e('currentTaxes() / graduated()'),'ON_CHAIN_VERIFIED_UNITS'),unit:'percent',rawBps:rates[0].toString(),configuredPercent:Number(rates[0])/100,scope:'Non-exempt transfers from the configured mainPool after graduation'};result.sellTax={...c.fact(active?Number(rates[1])/100:0,e('currentTaxes() / graduated()'),'ON_CHAIN_VERIFIED_UNITS'),unit:'percent',rawBps:rates[1].toString(),configuredPercent:Number(rates[1])/100,scope:'Non-exempt mainPool sells: surcharge on remaining seller balance, capped at remaining balance. Not deducted from pool input.'};result.graduated=c.fact(active,e('graduated()'));}catch(err){const f=c.failure(err);result.buyTax=c.unknown('Verified tax getter or graduation-state read failed.','VERIFIED_TAX_GETTER_FAILED',f.dataState);result.sellTax={...result.buyTax};result.taxReadFailure=f;}
try{if(probes[1].status!=='fulfilled')throw probes[1].reason;const cfg=words(probes[1].value,8);if(cfg.slice(0,2).some(x=>x>1000n)||cfg[2]+cfg[3]+cfg[4]!==10000n)throw Error();result.burnAllocation={...c.fact(Number(cfg[3])/100,e('config().burnBps'),'ON_CHAIN_VERIFIED_UNITS'),rawBps:cfg[3].toString(),scope:'Configured net processor allocation after bounty/protocol deductions; not a verified gross-tax burn percentage.'};result.feeWallet=c.addressWord('0x'+probes[1].value.slice(2+5*64,2+6*64));result.configRaw=cfg.map(x=>x.toString());}catch(err){result.burnAllocation=c.unknown('Verified config tuple could not be read or validated.','CONFIG_GETTER_FAILED',c.failure(err).dataState);}
if(control.owner.value!==null){result.taxSettingsMutable={...c.fact(control.owner.value!==c.BURNS[0],e('Verified reduceTaxes(uint16,uint16): msg.sender == owner; down-only'),'VERIFIED_SOURCE_AND_STATE'),scope:'Owner may only reduce configured buy/sell rates. Expired tax cannot be rearmed; this does not promise a currently positive rate.'};}
if(probes[3].status==='fulfilled'){try{result.mainPool=c.addressWord(probes[3].value);}catch{}}
if(probes[4].status==='fulfilled'){try{result.taxProcessor=c.addressWord(probes[4].value);const code=await c.rpc('eth_getCode',[result.taxProcessor,control.block]);const m=code.match(/^0x363d3d373d3d3d363d73([0-9a-f]{40})5af43d82803e903d91602b57fd5bf3$/i);const address=m?'0x'+m[1]:result.taxProcessor;const target=m?await c.rpc('eth_getCode',[address,control.block]):code;result.taxProcessorEvidence=require('../lib/verified-source').summary(await require('../lib/verified-source').lookup(address,target));result.buybackAndBurn=c.unknown('Tax processor was resolved, but no reviewed, bytecode-matched processor/buyback flow is established.','PROCESSOR_BUYBACK_FLOW_NOT_VERIFIED',result.taxProcessorEvidence.dataState==='SOURCE_API_FAILED'?'SOURCE_API_FAILED':'NOT_VERIFIED');}catch(err){result.taxProcessorFailure=c.failure(err);}}
return result;}return fallback(result,a);}
module.exports=require('../lib/search-request').route(async a=>require('../lib/contract-summary').present(await analyze(a)));module.exports.words=words;

async function fallback(result,a){if(['buyTax','sellTax','transferTax'].some(k=>result[k].value===null)){try{const s=await require('../lib/goplus').read(a);result.securitySource=s;for(const [key,sourceKey]of [['buyTax','buy_tax'],['sellTax','sell_tax'],['transferTax','transfer_tax']]){if(result[key].value===null&&result[key].reasonCode!=='V4_HOOK_FEE_NOT_VERIFIED'){const candidate=require('../lib/goplus').tax(s,sourceKey);if(candidate.value!==null){result[key]=candidate;result.dataState='DATA_FOUND';}}}result.poolFees=s.data?.dex?.map(p=>({pool:p.pair,type:p.liquidity_type,poolManager:p.pool_manager,feeFraction:p.pool_fee??null,source:'GoPlus',scope:'Pool fee is additional to token tax; absence is not zero.'}))||[];if(result.taxSettingsMutable.value===null){const candidate=require('../lib/goplus').flag(s,'slippage_modifiable');if(candidate.value!==null)result.taxSettingsMutable=candidate;}}catch(e){result.securitySourceFailure=require('../lib/core').failure(e);}}return result;}
